### ISSUE TITLE
Zowe Roadmap

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#103]
Related to #40 and #91.

The Zowe organization should provide a public roadmap we can point to for big-ticket items we are working on / thinking about implementing over the course of the next 6-12 months. 

This document should **not** promise a release timeline as its purpose is to instead outline our technical direction.

Roadmap items should include items squads will be working on in 6-12 months, as well as cross-squad or cross-functional items.

**Comment by armstro** [comment]
This issue to be transfer in the TSC once formed - the idea is TSC will assist in PI planning and provide roadmap outlook based on backlog and priorities.

**Comment by MarkAckert** [comment]
PI Planning activities, which can be found in the community repo, are the best place to find roadmap items.
