### ISSUE TITLE
Planning for Zowe Face to Face for Aug 4, 2019 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#113]
Need to discuss and close on face to face meeting agenda, topics and owners to lead sessions. Draft agenda here - https://ibm.box.com/s/mat95ff9hltulesxdcusue9q7j6lv2qn 

Example issues to finalize is session start time (are attendees willing to travel Saturday for early Sunday start or assume Sunday morning travel with noon time start), how many topics to try to cover - current assumption is one main tent - the meeting space has some accommodations for breakouts.

**Comment by jmertic** [comment]
So three things:

- Let's move out of box and into wiki.zowe.org
- Is that doc still accurate? I know the evening activity is still listed here and that's no longer applicable
- Let's remove the mentions of SHARE since this isn't officially connected to that event.

@Tbr00ksy

**Comment by Tbr00ksy** [comment]
Great event everyone!

link to assets: https://github.com/zowe/community/tree/master/Project%20Management/2019%20Face%20to%20Face
