### ISSUE TITLE
Process Document Updates

### ISSUE THREAD

**Issue by hogstrom** [zowe/zac#118]
Review documents in [branch 20190418-process-updates](https://github.com/zowe/zlc/tree/20190418-process-updates)

**Comment by jplinardon** [comment]
All documents reviewed.

**Comment by armstro** [comment]
One action item from the prior ZLC was to research who is considered a "valid voter" for the upcoming elections.....I think we all agree that committers are the voter pool but there was some question on whether it would be all committers from the beginning of the project or some filter applied (i.e., last 6 months or last 12 months for example). Many thanks to @Tbr00ksy for experimenting with a GrimoireLab dashboard on the Zowe github to allow us to look at committers over the past year.......the dashboard allows pre-canned time periods to be queried (a week, month, 90 days, etc.). 

The dashboard shows **130 committers did some github "activity" over the past year** - "activity" is what I consider a "meaningful action" like raise an issue, do a pull, close an issues, etc. (In comparison, if you look at the last 6 months there were 109 committers.) 

I propose we set a policy of committers who have been active over the past 12 months - **we still need to pick a date for starting point? Aug 1?** The 130 is both a manageable number and represent a quorum of people active on the project. 

[Zowe Git Stats.pptx](https://github.com/zowe/zlc/files/3305657/Zowe.Git.Stats.pptx)

**Comment by hogstrom** [comment]
Updated and merged
