### ISSUE TITLE
Set commit process w/ identified approvers

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zac#14]
Allow teams to create their own branch. Master would be managed by a small set of core contributors and is updated through pull requests. Initial membership based on people who did most commits in prior giza foundation work. Add the top two committers. If there is a third that can be added based on affiliation for now that would be ideal. Teams to decide. Sean Grady to document.

**Comment by 1000TurquoisePogs** [comment]
Here are the top 2 contributors, but migrated repositories, and the links to where I found this info.

| Repo | Top 2 Contributors |
| ------ | ----------------------- |
| [zlux-example-server](https://github.com/gizafoundation/zlux-example-server/graphs/contributors) | @1000TurquoisePogs @eamondawes |
| [zlux-build](https://github.com/gizafoundation/zlux-build/graphs/contributors) | @eamondawes @1000TurquoisePogs |
| [zlux-app-manager](https://github.com/gizafoundation/zlux-app-manager/graphs/contributors) | @colavitam @1000TurquoisePogs |
| [react-sample-app](https://github.com/gizafoundation/react-sample-app/graphs/contributors) | @colavitam |
| [imperative](https://github.com/gizafoundation/imperative/graphs/contributors) | @ChrisBoehmCA @AHumanFromCA | 
| [zlux-proxy-server](https://github.com/gizafoundation/zlux-proxy-server/graphs/contributors) | @1000TurquoisePogs @fkovinAtRocket |
| [orion-editor-component](https://github.com/gizafoundation/moved-orion-editor-component/graphs/contributors) | @jordanCain @jackjia-ibm |
| [zowe-install-packaging](https://github.com/gizafoundation/moved-zoe-install-packaging/graphs/contributors) | @Joe-Winchester @jackjia-ibm |
| [zlux-workflow](https://github.com/gizafoundation/zlux-workflow/graphs/contributors) | @lchudinov @rpenny125 |
| [zlux-grid](https://github.com/gizafoundation/zlux-grid/graphs/contributors) | @AlexanderMikhailovAtRocket @eamondawes |
| [zlux-widgets](https://github.com/gizafoundation/zlux-widgets/graphs/contributors) | @shosen993 @rpenny125 |
| [zosmf-auth](https://github.com/gizafoundation/zosmf-auth/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [tn3270-ng2](https://github.com/gizafoundation/tn3270-ng2/graphs/contributors) | @1000TurquoisePogs @eamondawes |
| [zlux-editor](https://github.com/gizafoundation/zlux-editor/graphs/contributors) | @1000TurquoisePogs |
| [file-transfer-app](https://github.com/gizafoundation/file-transfer-app/graphs/contributors) | @dprizentsov @1000TurquoisePogs |
| [vt-ng2](https://github.com/gizafoundation/vt-ng2/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [zowe-install-test](https://github.com/gizafoundation/moved-zowe-install-test/graphs/contributors) | @jackjia-ibm |
| [explorer-mvs](https://github.com/gizafoundation/moved-explorer-mvs/graphs/contributors) | @jordanCain @Colin-Stone |
| [zos-subsystems](https://github.com/gizafoundation/zos-subsystems/graphs/contributors) | @rpenny125 @1000TurquoisePogs |
| [zlux-shared](https://github.com/gizafoundation/zlux-shared/graphs/contributors) | @1000TurquoisePogs @EugenyPavluk |
| [zlux](https://github.com/gizafoundation/zlux/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [workshop-user-browser-app](https://github.com/gizafoundation/workshop-user-browser-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [sample-iframe-app](https://github.com/gizafoundation/sample-iframe-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [zlux-ng2](https://github.com/gizafoundation/zlux-ng2/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [zlux-platform](https://github.com/gizafoundation/zlux-platform/graphs/contributors) | @1000TurquoisePogs @jordanfilteau1995 |
| [zss-auth](https://github.com/gizafoundation/zss-auth/graphs/contributors) | @rpenny125 @1000TurquoisePogs |
| [explorer-server-auth](https://github.com/gizafoundation/explorer-server-auth/graphs/contributors) | @jordanCain @stevenhorsman-ibm |
| [zlux-file-properties](https://github.com/gizafoundation/zlux-file-properties/graphs/contributors) | @rpenny125 @1000TurquoisePogs |
| [workshop-starter-app](https://github.com/gizafoundation/workshop-starter-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 |
| [zlux-file-explorer](https://github.com/gizafoundation/zlux-file-explorer/graphs/contributors) | @LongBu @DivergentEuropeans |
| [zlux-charts](https://github.com/gizafoundation/zlux-charts/graphs/contributors) | @AlexanderMikhailovAtRocket @eamondawes |
| [sample-app](https://github.com/gizafoundation/sample-app/graphs/contributors) | @1000TurquoisePogs @EugenyPavluk |
| [explorer-uss](https://github.com/gizafoundation/moved-explorer-uss/graphs/contributors) | @jordanCain @Colin-Stone |
| [explorer-jes](https://github.com/gizafoundation/moved-explorer-jes/graphs/contributors) | @jordanCain @Colin-Stone |
| [explorer-utilities](https://github.com/gizafoundation/moved-atlas-utilities/graphs/contributors) | @stevenhorsman-ibm @jackjia-ibm |
| [explorer-server](https://github.com/gizafoundation/moved-atlas-server/graphs/contributors) | @Colin-Stone @stevenhorsman-ibm |
| [explorer-model](https://github.com/gizafoundation/moved-atlas-model/graphs/contributors) | @stevenhorsman-ibm @Colin-Stone |
| [explorer-server-tests](https://github.com/gizafoundation/moved-atlas-server-tests/graphs/contributors) | @stevenhorsman-ibm @jackjia-ibm |
| [rest-api-jzos-sample](https://github.com/gizafoundation/moved-rest-api-jzos-sample/graphs/contributors) | @Colin-Stone @jackjia-ibm |

**Comment by 1000TurquoisePogs** [comment]
In the case of Rocket contributions, some of the top committers do not show up as such as a result of how we migrated code into this public github. I think the list of initial repo gatekeepers should actually be amended by the people on this list either accepting the role or recommending someone to take their place. For example: zlux-build lists myself as the second contributor but in reality, I believe @nosrednayduj knows it better than I do.
Does this sound like a good plan?

**Comment by hogstrom** [comment]
As a bootstrap effort I think that will work because of the transition.  I suggest that this is a limited time activity and we should lock this down in the next few weeks.  Then its meritocracy based so there is no appearance of vendor movement of people in and out of the project.  Does that make sense ?

Matt Hogstrom
matt@hogstrom.org
+1-919-656-0564
PGP Key: 0x90ECB270
Facebook <https://facebook.com/matt.hogstrom>  LinkedIn <https://linkedin/in/mhogstrom>  Twitter <https://twitter.com/hogstrom>

“It may be cognitive, but, it ain’t intuitive."
— Hogstrom

**Comment by 1000TurquoisePogs** [comment]
If there's agreement, I'd like it to be done sometime this or next week to get into a shape where we can reviewing and accepting commits from people who weren't grandfathered into the repositories. I agree that it should be meritocratic after the initial setup, but the process of change over time isn't clear to me. Such as: is each repository determining metrics of merit independently or is there a standard measurement (percentage of code that is yours over all of time or just a moving window, community vote, some other means) that the ZLC is using to guide the community? Do you have suggestions based off of working with Apache?

**Comment by rpenny125** [comment]
Sean, regarding your questions about metrics, etc. (as it relates to ongoing managing of "core contributors"), I think some of this is covered in the Zowe charter: https://zowe.org/Zowe-Charter.pdf, in the section headed "Contributors and Committers:"

Speaking of which, the terminology of the charter has:

> Contributors are individuals who contribute code,
> fixes, tests, documentation, or other work that is part of the project. Committers have write
> access to the project's resources (source code repository, bug tracking system, website, build
> server, downloads, etc.) and are expected to influence the project's development.

@hogstrom  by "core contributors", do you mean those whom the charter refers to as "committers"? If the charter terminology is non-standard, we should probably discuss that at some point.

**Comment by 1000TurquoisePogs** [comment]
You're right - the charter explains this clearly. Thanks!

**Comment by Tbr00ksy** [comment]
@hogstrom @1000TurquoisePogs the on-boarding squad needs some help with committers though. For non-code related items such as website changes, content creation (tutorials, samples, etc.), Waffle/Github issue management, we need a set of committers as well. For example, @jayenzi should be a committer for Zowe.org and I need write access as the scrum master to help manage waffle tickets. Can we set up a similar process for accepting commits for non-code community assets?

**Comment by 1000TurquoisePogs** [comment]
Here are the list of 3 Committers, but migrated repositories, and the links to where I found this info.
This list is altered in that repositories where people from Rocket knew best, some Rocket people were swapped out for others to get a good mix of knowledge and availability. I'd recommend others do the same where they can.
Some repositories did not have 3 contributors, so I added more based on who I thought had subject knowledge.

Note: substituted @dkelosky for @jhenryRocket for workshop-user-browser-app after asking @dkelosky if he preferred to be a committer or not.

| Repo | Initial 3 Committers |
| ------ | ----------------------- |
| [zlux-example-server](https://github.com/gizafoundation/zlux-example-server/graphs/contributors) | @1000TurquoisePogs @eamondawes @fkovinAtRocket |
| [zlux-build](https://github.com/gizafoundation/zlux-build/graphs/contributors) | @eamondawes @nosrednayduj @1000TurquoisePogs |
| [zlux-app-manager](https://github.com/gizafoundation/zlux-app-manager/graphs/contributors) | @colavitam @1000TurquoisePogs @lchudinov |
| [react-sample-app](https://github.com/gizafoundation/react-sample-app/graphs/contributors) | @colavitam @1000TurquoisePogs @jordanfilteau1995 |
| [imperative](https://github.com/gizafoundation/imperative/graphs/contributors) | @ChrisBoehmCA @AHumanFromCA @tucker01 | 
| [zlux-proxy-server](https://github.com/gizafoundation/zlux-proxy-server/graphs/contributors) | @1000TurquoisePogs @fkovinAtRocket @rpenny125 |
| [orion-editor-component](https://github.com/gizafoundation/moved-orion-editor-component/graphs/contributors) | @jordanCain @jackjia-ibm @stevenhorsman-ibm |
| [zowe-install-packaging](https://github.com/gizafoundation/moved-zoe-install-packaging/graphs/contributors) | @Joe-Winchester @jackjia-ibm @stevenhorsman-ibm |
| [zlux-workflow](https://github.com/gizafoundation/zlux-workflow/graphs/contributors) | @lchudinov @rpenny125 @1000TurquoisePogs |
| [zlux-grid](https://github.com/gizafoundation/zlux-grid/graphs/contributors) | @AlexanderMikhailovAtRocket @1000TurquoisePogs @rpenny125 |
| [zlux-widgets](https://github.com/gizafoundation/zlux-widgets/graphs/contributors) | @rpenny125 @DenisGlebov @1000TurquoisePogs |
| [zosmf-auth](https://github.com/gizafoundation/zosmf-auth/graphs/contributors) | @fkovinAtRocket @1000TurquoisePogs @rpenny125 |
| [tn3270-ng2](https://github.com/gizafoundation/tn3270-ng2/graphs/contributors) | @1000TurquoisePogs @eamondawes @rpenny125  |
| [zlux-editor](https://github.com/gizafoundation/zlux-editor/graphs/contributors) | @colavitam  @jordanfilteau1995 @1000TurquoisePogs |
| [file-transfer-app](https://github.com/gizafoundation/file-transfer-app/graphs/contributors) | @dprizentsov @jordanfilteau1995 @1000TurquoisePogs |
| [vt-ng2](https://github.com/gizafoundation/vt-ng2/graphs/contributors) | @1000TurquoisePogs  @eamondawes @rpenny125 |
| [zowe-install-test](https://github.com/gizafoundation/moved-zowe-install-test/graphs/contributors) | @jackjia-ibm @Joe-Winchester ? @stevenhorsman-ibm ?|
| [explorer-mvs](https://github.com/gizafoundation/moved-explorer-mvs/graphs/contributors) | @jordanCain @Colin-Stone @stevenhorsman-ibm |
| [zos-subsystems](https://github.com/gizafoundation/zos-subsystems/graphs/contributors) | @rpenny125 @1000TurquoisePogs @joenemo |
| [zlux-shared](https://github.com/gizafoundation/zlux-shared/graphs/contributors) | @1000TurquoisePogs @rpenny125 @colavitam |
| [zlux](https://github.com/gizafoundation/zlux/graphs/contributors) | @1000TurquoisePogs @rpenny125 @colavitam |
| [workshop-user-browser-app](https://github.com/gizafoundation/workshop-user-browser-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 @jhenryRocket |
| [sample-iframe-app](https://github.com/gizafoundation/sample-iframe-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 @colavitam |
| [zlux-ng2](https://github.com/gizafoundation/zlux-ng2/graphs/contributors) | @1000TurquoisePogs @rpenny125 @colavitam |
| [zlux-platform](https://github.com/gizafoundation/zlux-platform/graphs/contributors) | @1000TurquoisePogs @colavitam @rpenny125 |
| [zss-auth](https://github.com/gizafoundation/zss-auth/graphs/contributors) | @fkovinAtRocket  @rpenny125 @1000TurquoisePogs |
| [explorer-server-auth](https://github.com/gizafoundation/explorer-server-auth/graphs/contributors) | @jordanCain @stevenhorsman-ibm @1000TurquoisePogs ? |
| [zlux-file-properties](https://github.com/gizafoundation/zlux-file-properties/graphs/contributors) | @rpenny125 @1000TurquoisePogs @colavitam |
| [workshop-starter-app](https://github.com/gizafoundation/workshop-starter-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 @jhenryRocket |
| [zlux-file-explorer](https://github.com/gizafoundation/zlux-file-explorer/graphs/contributors) | @rpenny125 @colavitam @1000TurquoisePogs |
| [zlux-charts](https://github.com/gizafoundation/zlux-charts/graphs/contributors) | @AlexanderMikhailovAtRocket @rpenny125 @1000TurquoisePogs |
| [sample-app](https://github.com/gizafoundation/sample-app/graphs/contributors) | @1000TurquoisePogs @rpenny125 @jordanfilteau1995 |
| [explorer-uss](https://github.com/gizafoundation/moved-explorer-uss/graphs/contributors) | @jordanCain @Colin-Stone @stevenhorsman-ibm |
| [explorer-jes](https://github.com/gizafoundation/moved-explorer-jes/graphs/contributors) | @jordanCain @Colin-Stone @stevenhorsman-ibm |
| [explorer-utilities](https://github.com/gizafoundation/moved-atlas-utilities/graphs/contributors) | @stevenhorsman-ibm @jackjia-ibm @jordanCain |
| [explorer-server](https://github.com/gizafoundation/moved-atlas-server/graphs/contributors) | @Colin-Stone @stevenhorsman-ibm @jackjia-ibm |
| [explorer-model](https://github.com/gizafoundation/moved-atlas-model/graphs/contributors) | @stevenhorsman-ibm @Colin-Stone @jackjia-ibm |
| [explorer-server-tests](https://github.com/gizafoundation/moved-atlas-server-tests/graphs/contributors) | @stevenhorsman-ibm @jackjia-ibm @Colin-Stone |
| [rest-api-jzos-sample](https://github.com/gizafoundation/moved-rest-api-jzos-sample/graphs/contributors) | @Colin-Stone @jackjia-ibm @stevenhorsman-ibm |

**Comment by 1000TurquoisePogs** [comment]
Completed this by implementing Committer teams and locking down master to require pull request approvals.
