### ISSUE TITLE
Zowe Community Access to New Website and Download Metrics

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#141]
With the cut-over to the new Zowe.org site, how is the community to access data and generate the monthly metrics reporting? Are there process that need to change or access that needs to be granted?

**Comment by jmertic** [comment]
We've granted out access to Google Analytics, which should provide access to any of these items that are needed.

We do need to move the docs site over to this Google Analytics as well. Probably best if you make a pull request as I'm not sure all the places to have it updated.

**Comment by armstro** [comment]
@TaylorDonner in ZLC discussion today there was question on whether this issue can be closed? Assumption is yes - You regularly provide reporting on zowe.org - we will close and reopen if needed.
