### ISSUE TITLE
Approval to promote Zowe v1.5.0 RC3 as GA

### ISSUE THREAD

**Issue by nkocsis** [zowe/zac#148]
We are requesting to ship RC3

Build #37 is promoted as Zowe v1.5.0-RC3, you can download from:
https://gizaartifactory.jfrog.io/gizaartifactory/libs-release-local/org/zowe/1.5.0-RC3/zowe-1.5.0-RC3.pax
or:
https://projectgiza.org/builds/stable/1.5.0-RC3/zowe-1.5.0-RC3.pax
The CLI Standalone Package is published here:
https://gizaartifactory.jfrog.io/gizaartifactory/libs-release-local/org/zowe/1.5.0-RC3/zowe-cli-package-1.5.0-RC3.zip
or:
https://projectgiza.org/builds/stable/1.5.0-RC3/zowe-cli-package-1.5.0-RC3.zip

**Comment by armstro** [comment]
+1 

 
Bruce Armstrong 
IBM System Z Offering Manager- zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: armstrob@us.ibm.com
Tel: 919-254-8773
Cell: 919-931-3132
