### ISSUE TITLE
Zowe Training and Digital Badge - ZLC discussion - request to OMP 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#149]
3rd party has been offering free Zowe education and badge -  work with the OMP has stalled and education is being withdrawn. The education is to the benefit of the community when many people are hungry for education. Request discussion to get facts on the request to OMP and status plus how we can help.

**Comment by jmertic** [comment]
Maybe we could setup a call to chat on this? ( noticed you kept this very vague so perhaps you'd rather handle offline ). Also this sounds like a potential vendor product question which is outside the scope of the ZLC IIRC.

**Comment by armstro** [comment]
Sure - the call is the ZLC next week as I do think the zlc need to be 
understand - you should already be aware of the situation - involves 
Interskill Learning - 


 
Bruce Armstrong 
IBM System Z Offering Manager- zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: armstrob@us.ibm.com
Tel: 919-254-8773
Cell: 919-931-3132

**Comment by armstro** [comment]
I'm told issue resolved - thanks John - no need for ZLC discussion 

https://www.youracclaim.com/org/ibm/badge/interskill-basics-for-zowe
