### ISSUE TITLE
OMP Landing page imagery

### ISSUE THREAD

**Issue by jayenzi** [zowe/zac#15]
![omp_landing_image](https://user-images.githubusercontent.com/39416146/44749576-e9ff0280-aae0-11e8-862d-e6cd726f7fc8.jpg)

Can we look at changing the imagery on the OMP landing page that promotes Zowe?  We should at least strive for a minimum AA WCAG compliance.  The text is being lost on the light parts of the background image and making it difficult to read.

**Comment by hogstrom** [comment]
I'd like to move this to the documentation group.  Objections ?

Note to Jaty from Matt and then close.

**Comment by hogstrom** [comment]
This is an old issue and has been resolved post launch.
