### ISSUE TITLE
Promote CLI plugin from incubation to active

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#153]
The `zowe-cli-ftp-plugin` is considered ready by developers to be included in the Zowe CLI bundle we link to on zowe.org. 

What is the process this plugin should follow to be promoted into the Zowe CLI bundle? Is it the same as migrating a subproject from `incubation` to `active`, or different? Does this require squad approval, ZLC approval, or both?

**Comment by MarkAckert** [comment]
This is the checklist the squad came up with:

- Documentation and Naming
- Automated build and test
- EPL 2.0 License 
- NPM audit
- Security scanning 
- Documentation peer-review 
- UX review 
- Automated deployment to staging artifactory (currently Giza)
- Automated deployment to public NPM
- TPSRs 

I think we should create a doc in the ZLC with this checklist, focused on the steps required for any component to be included in a zowe.org deliverable.

Thoughts?

**Comment by armstro** [comment]
@MarkAckert reminder to review and close if appropriate
