### ISSUE TITLE
Archival of historical builds (<1.0.0)

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#156]
As part of the transition from GizaArtifactory to LF Artifactory, we are transferring artifacts from Giza -> LF in anticipation of Giza becoming unavailable in a few months time.

We are focused on **release** artifacts only, but for release artifacts versioned under **1.0.0**, the distribution was NOT EPL-2.0.  

Are there any legal issues hosting non-EPL artifacts on LF Artifactory, and if so, what are our options for archiving these artifacts?

**Comment by armstro** [comment]
Let's discuss at 11/27/19 ZLC meeting but I do not see a reason to carry these builds forward to the LF Artifactory. Likely need agreement from @jmertic . These being non EPL2.0 and knowing there are  security improvements in 1.x levels I would not carry these forward.

**Comment by jmertic** [comment]
We cannot host these artifacts in the LF Artifactory - and frankly they shouldn't be something directly available through the project period. If one of IBM/Broadcom/Rocket wants to host them, then they could per the previous agreement ( though I thought that had expired ).
