### ISSUE TITLE
Zowe Sub-Project Proposal: Zowe on the go (Mobile App)

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#157]
- **Name of project (must be unique within Zowe)**

Zowe on the go

 "Interacting with Zowe from your mobile device is now within reach" 

- **Project description (what it does, why it is valuable, origin and history)**

This project was developed during a Zowe Hackathon at Broadcom. The goal of this project was to develop a fast, on-the-move identification/triage application for mainframe operations and systems support.
"As an on-call support, my immediate needs are to check the status of running services and to perform a number of jobs services: get a list of jobs, get content from a job file output, submit a job, and more." 
This project adds another way modern developers and system/operations support interact with the mainframe, built against Zowe API Mediation Layer, thus bringing more value to the Zowe ecosystem and its adopters.
 

- **Statement on alignment with Zowe mission**

The mobile application aligns with Broadcom’s direction to support and contribute to Zowe. The applications ties directly into Zowe (see project description).
 

- **Sponsor from ZLC (sponsor helps mentor projects)**

Mark Ackert, Jean-Louis
 
- **License and contribution guidelines**

To be contributed as Eclipse Public License 2.0
 
- **Source control** 	

Github 
(Public Repository Link to be added)
 
- **External dependencies (including licenses)**
  * Ionic - MIT License
  * Apache Cordova - Apache 2.0 License
  * Angular - MIT License

- **Initial committers**
  * Jessielaine Punongbayan
  * David Janda
  * Marketa Muzikova
  * Richelle Anne Craw
 
- **Infrastructure requests (CI / OMP Cluster)**

N/A (Use existing Zowe build infrastructure)
 
- **Communication channels (Slack, irc, mailing lists)**

Slack Channel
 
- **Issue tracker (GitHub by default)**

Github
 
- **Preferred maturity level** 

Incubation

**Comment by MarkAckert** [comment]
@jellypuno @crawr @jandadav @muzikovam @zowe/zlc 

All, this is the sub-project proposal as brought up on the ZLC this week.

The team is planning to present/discuss the proposal to the ZLC on the January 15th meeting, and a public Github repository with the corresponding code should be added next week.

Please review this proposal prior to the January 15th date. Thank you!

**Comment by jplinardon** [comment]
I have a few questions:

1. Would this project be a mobile application only or would it/could it be considered a framework for Zowe mobile application development
2. What considerations are provided for authentication and communication security
3. Given the stated purpose of monitoring services and jobs, would a backend/server be part of this project, or would it only poll existing APIs?

**Comment by jellypuno** [comment]
Hi @jplinardon 

> Would this project be a mobile application only or would it/could it be considered a framework for Zowe mobile application development

At its current state, It is a mobile application that accesses Zowe Services through REST APIs. Will it be a framework for future Zowe mobile development? This is open for discussion. 

> What considerations are provided for authentication and communication security

We are communicating with API Mediation Layer in terms of authentication with credentials. Currently we are using Basic Authentication to access the services. But in future, when the changes are available in API-ML, we can use tokens and maybe 2FA.

> Given the stated purpose of monitoring services and jobs, would a backend/server be part of this project, or would it only poll existing APIs?

It is only using existing APIs. Basically, the concept that we have is to fire APIs that are available in z/OS and discovered by API ML. We are accessing via the base URL provided by Mediation Layer.

**Comment by jellypuno** [comment]
- Source control

Github
https://github.com/jellypuno/Zowe-on-the-go

**Comment by armstro** [comment]
Many thanks to the team for the presentation - would someone please post the slides that describe the project. I will discuss with OMP (John Mertic) on how we get the code scanned and included into the project. Posting the slides here would be great for future reference.

**Comment by jellypuno** [comment]
Hi, I have added the slides in the repo: https://github.com/jellypuno/Zowe-on-the-go/tree/master/app/resources/presentation

**Comment by MarkAckert** [comment]
Contribution complete; closing.
