### ISSUE TITLE
Zowe Press Coverage To be Listed on Zowe.org

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#16]
@jayenzi Can we list or create a news feed of Zowe coverage on Zowe.org somewhere?

Here's my current list:
ZDNet: https://www.zdnet.com/article/zowe-bringing-the-mainframe-to-the-open-source-world/
OMP Press Release: https://www.openmainframeproject.org/press/2018/08/28/open-mainframe-project-announces-the-launch-of-zowe-an-open-source-framework-that-strengthens-integration-with-modern-enterprise-applications
LeMagIT: https://www.lemagit.fr/actualites/252447710/Open-Source-avec-Zowe-IBM-CA-et-Rocket-Software-veulent-depoussierer-Z-OS
PacktHub: https://hub.packtpub.com/introducing-zowe-a-new-open-source-framework-to-simplify-development-on-z-os-backed-by-ibm/
Converge Network Digest: https://www.convergedigest.com/2018/08/open-source-zowe-framework-bridges-apps.html
DZone: https://dzone.com/articles/open-source-platform-strengthens-integration-with?utm_content=76358868&utm_medium=social&utm_source=twitter
Solutions Review: https://solutionsreview.com/cloud-platforms/open-mainframe-project-zowe/
Barry Baker Blog: https://www.ibm.com/blogs/systems/open-source-project-zowe-fast-simple-familiar-zos-development/?cm_mmc=OSocial_Twitter-_-Systems_Systems+-+Infrastructure-_-WW_WW-_-Zowe+Logo
Tuxmachines: http://www.tuxmachines.org/node/114948?quicktabs_bottomtabs=0
Mainframe Debate: https://mainframedebate.com/2018/08/23/raising-zowe-a-community-to-bring-developers-together/
Tim Brooks Blog: https://developer.ibm.com/code/2018/08/23/zowe-open-source-project-mainframe/
Matt Hogstrom LinkedIn Blog: https://www.linkedin.com/pulse/zowe-opensource-zos-really-matt-hogstrom/

**Comment by hogstrom** [comment]
Tim I'm going to ask if you can help here ... if not, can you tap someone else on the shoulder?

**Comment by Tbr00ksy** [comment]
IBM System Mag: http://ibmsystemsmag.com/mainframe/trends/whatsnew/open-source-zowe-project/?utm_source=SilverpopMailing&utm_medium=email&utm_campaign=091118-Z-EXTRA%20(1)%20Live%20Send&utm_content=Getting%20to%20Know%20the%20Open%20Source%20Zowe%20Project&spMailingID=14219622&spUserID=MTMzMjEwNjg1NzA2S0&spJobID=1480810092&spReportId=MTQ4MDgxMDA5MgS2

**Comment by jmertic** [comment]
Press coverage doesn't need to be on Zowe.org - this site is a community site and not a marketing one. Let's close this.

**Comment by hogstrom** [comment]
Add a page that points back to the OMP press links

**Comment by Tbr00ksy** [comment]
Mae will update the "In The News" Page and Zowe.org will point to it: https://www.openmainframeproject.org/news/in-the-news

**Comment by hogstrom** [comment]
Tim, I'm closing this as it sounds like the plan is in motion.
