### ISSUE TITLE
Proposal for a new Zowe landscape diagram

### ISSUE THREAD

**Issue by solsu01** [zowe/zac#160]
As discussed in ZLC meeting 2/12, let's collaborate on updating the Zowe landscape diagram with the new sub-projects like Mobile App and ZDK (Python, NodeJS).
[zowe_landscape_update.pptx](https://github.com/zowe/zlc/files/4192974/zowe_landscape_update.pptx)

**Comment by armstro** [comment]
I have added Sean for his review of the slide - also trying to add Peter Fandel but checking with him on whether he has OMP/Zowe github id.

**Comment by PeterFandelAtRocket** [comment]
'off-host' is probably not the term you want but I was thinking something like this
[zowe_offhost_clientSDK.pptx](https://github.com/zowe/zlc/files/4204673/zowe_offhost_clientSDK.pptx)

**Comment by solsu01** [comment]
Thanks for the review!

On the "off-host" term - I am not sure if that's needed in addition to "client". In fact, I don't think there's anything stopping someone from building a python (thanks to Rocket..) or node app using this SDK that runs on z/OS - sorry if I miscommunicated this on the ZLC call.

The "Client" part of SDK just shows that this SDK is a client of server side REST APIs, but the client could be an app running on z/OS or off-platform.

**Comment by Joe-Winchester** [comment]
[zowe_landscape_update 01.pptx](https://github.com/zowe/zlc/files/4214254/zowe_landscape_update.01.pptx)
 @solsu01 - I've added a 02 chart to the deck with what I think the landscape chart could show - it's not polished but I wanted to 
- capture more about the extensibility of Zowe, where the conformance program relates to each part of the landscape
- capture more of existing runtimes that Zowe works with and also conformant runtimes
- show more about the value of the APIML in terms of SSO, gateway, ...
   
I'll try to put more polish on the slide but heads down trying to get Zowe 1.9 out the door the next couple of days !   Many thanks for taking the initiative on getting this slide updated.

**Comment by solsu01** [comment]
Updates from ZLC call 2/19
Cartier is ok to use this ppt at SHARE: 
[zowe_clientSDK.pptx](https://github.com/zowe/zlc/files/4225914/zowe_clientSDK.pptx)

For the longer term updated landscape diagram, we'll continue to iterate and refine this ppt: 
[zowe_landscape_update.02.pptx](https://github.com/zowe/zlc/files/4225980/zowe_landscape_update.02.pptx)

**Comment by armstro** [comment]
Looks good to me (who didn't know the knot of snakes logo).....thanks for 
the edits 


 
Bruce Armstrong 
IBM System Z Offering Manager- zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: armstrob@us.ibm.com
Tel: 919-254-8773
Cell: 919-931-3132

**Comment by solsu01** [comment]
I have had a lot of requests from squad leads, users and the community for an updated landscape diagram, so I've taken another stab at it with the intent of keeping it simple, but covering all the high level active sub-projects and incubation sub-projects: 
[zowe_landscape_update.03.pptx](https://github.com/zowe/zlc/files/4683906/zowe_landscape_update.03.pptx)

It would be helpful to settle on this as I'm noticing folks starting to create their own versions since there isn't a standard one to use.

**Comment by MarkAckert** [comment]
This looks good. I was playing around with the format to try and clarify client/user components from server components, but there's not much real estate to shuffle things around. I made an edit with the some arrows modifications - not sure if this clarifies the diagram or just makes it more busy. 

[zowe_landscape_update.04.pptx](https://github.com/zowe/zlc/files/4685948/zowe_landscape_update.04.pptx)

**Comment by jellypuno** [comment]
Hi, I would like to ask for your permission if I could use the updated Zowe landscape on the [upcoming webcast](https://community.broadcom.com/mainframesoftware/events/event-description?CalendarEventKey=5838c371-6c88-4767-a5a7-c603af600a61&CommunityKey=c581dd20-140f-4708-b335-eaacc07d6802&Home=%2fmainframesoftware%2fcommunities%2fcommunityhomeblogs) that I am going to present. I will briefly discuss about Zowe components and I would like the Zowe Mobile App to be part of it.

@MarkAckert @solsu01 I am confused with the arrows on update#04. Is the arrow pointing to APIML means that I am calling the APIML APIs? And the App Framework doesn't do that?

**Comment by Joe-Winchester** [comment]
@jellypuno - The API Mediation Layer is an edge server that is able to collate all of the z/OS services used by clients, so that there is one certificate and one endpoint port that needs to be surfaced to clients.  APIML also offers the ability to generate a one time use token for authentication that means it can support multi factor authentication (MFA) and for the credential challenge it only occurs once giving the user a single sign-on (SSO) experience.  The App Framework (aka web desktop) can be run on its own if a user wishes to, but by default with Zowe both the App Framework and APIML are started, and in this case the App Framework sees the APIML is running and will work behind it as shown in the diagram.  This means all of its function works through the APIML port,  and SSO occurs between its web desktop and the APIML catalog.  You're right that the Zowe Mobile App doesn't work via the APIML, I believe you just call out to the z/OSMF endpoints directly, but going forward having the mobile app work with the APIML is something that would be good to validate with users as a way going forward so that if you wanted to access other services behind the APIML (such as CICS, DB2, CA Endeavor, ...) then you could do so benefitting from SSO/MFA, single certificate, ...   Maybe it'd be good to explain that mobile is an incubator project and currently doesn't go via APIML, but as part of maturing to be a Zowe core app that's something being looked at to ensure there is a consistent experience across the suite.

**Comment by jellypuno** [comment]
@Joe-Winchester Thank you for the explanation. I appreciate it 😊

**Comment by armstro** [comment]
[Zowe slide from webinar .pptx](https://github.com/zowe/zlc/files/4688404/Zowe.slide.from.webinar.pptx)

I guess first comment is that I thought we were going to try to use the slide for the upcoming OMP webinar as the slide for what is Zowe? This was out growth of the ZLC working sessions (both words and pictures). Maybe this slide has not gotten wide enough review for us to settle on it. 

My second comment is maybe we should just admit that we are unlikely to decide on just one picture for Zowe. Comparing the OMP webinar slide to the 04 version above it looks like one provides more detail that a technical audience may care about. We should at least be consistent in whether Zowe components are at the top of the page or bottom. (I do like OMP slide rendering that shows plugs both out of the box (in blue) and custom extensions (in green)). 

Maybe we can take a few mins in the ZLC call today to discuss.....maybe we have a couple versions in a central location to be used depending on the audience and how comfortable the presenter is with the technical detail. I recall an attempt to have a github repo of slides at one time.

**Comment by solsu01** [comment]
> @jellypuno - The API Mediation Layer is an edge server that is able to collate all of the z/OS services used by clients, so that there is one certificate and one endpoint port that needs to be surfaced to clients. APIML also offers the ability to generate a one time use token for authentication that means it can support multi factor authentication (MFA) and for the credential challenge it only occurs once giving the user a single sign-on (SSO) experience. The App Framework (aka web desktop) can be run on its own if a user wishes to, but by default with Zowe both the App Framework and APIML are started, and in this case the App Framework sees the APIML is running and will work behind it as shown in the diagram. This means all of its function works through the APIML port, and SSO occurs between its web desktop and the APIML catalog. You're right that the Zowe Mobile App doesn't work via the APIML, I believe you just call out to the z/OSMF endpoints directly, but going forward having the mobile app work with the APIML is something that would be good to validate with users as a way going forward so that if you wanted to access other services behind the APIML (such as CICS, DB2, CA Endeavor, ...) then you could do so benefitting from SSO/MFA, single certificate, ... Maybe it'd be good to explain that mobile is an incubator project and currently doesn't go via APIML, but as part of maturing to be a Zowe core app that's something being looked at to ensure there is a consistent experience across the suite.

I believe the Mobile app does go through the API ML.

**Comment by solsu01** [comment]
As discussed on ZLC 6/3, I'm working on a "current" and "future" version of these slides by repurposing @PeterFandelAtRocket 's one from the OMP webinar (for current) and my previous rev in this issue (for future).

**Comment by solsu01** [comment]
Please review this version of "today" and "future" versions with inspiration from the webinar slide that Bruce shared:

[zowe_landscape_update_05.pptx](https://github.com/zowe/zlc/files/4801722/zowe_landscape_update_05.pptx)

If we are good with this, I'd like to place this in the zowe community github for others to use.

**Comment by armstro** [comment]
@solsu01 with "release" of this ppt in the PI planning do we want to consider this one closed?

**Comment by solsu01** [comment]
Yes, good with me to close.

https://github.com/zowe/community/tree/master/Templates
