### ISSUE TITLE
Create a slide set on "What is Zowe" for use by all 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#163]
This should also include an updated Zowe landscape slide that is commonly used in other presentations. Details are in https://github.com/zowe/zlc/issues/160

**Comment by armstro** [comment]
Please contribute "standard" Zowe decks you use so that we can consolidate for a single source for use by OMP members

**Comment by armstro** [comment]
[Zowe Overview 02-7-20 .pdf](https://github.com/zowe/zlc/files/4227237/Zowe.Overview.02-7-20.pdf)
OK - ppt to big so I am offering pdf just to show what a typical overview deck contains when presenting Zowe. We need to discuss how we collaborate to merge into a few slides.....I don't want to push everyone to box - do we do the work on Confluence?

**Comment by solsu01** [comment]
I've updated the may webinar zowe overview slides with the latest zowe landscape and uploaded it to zowe community github here: https://github.com/zowe/community/blob/master/ppt_templates/Zowe%20OverviewJuly2020.pptx

**Comment by Joe-Winchester** [comment]
Excellent deck @solsu01 - many thanks to you for pulling this together and everyone else who contributed.  Nice job
