### ISSUE TITLE
Zowe: Zeepy Contribution 

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#166]
This issue is to track donation of Zeepy to the Zowe organization. This has been previously discussed on the ZLC, but as there is currently no squad formed for Client APIs to manage the donation, the ZLC should vote on Zeepy's contribution.

Zeepy is a Python API for issuing z/OSMF REST calls, and was built by a community member, Guilherme Cartier. It is modeled after the Node API the Zowe CLI squad uses for issuing z/OSMF REST calls.

The code can be found here: https://github.com/gcartier94/zeepy

**Comment by solsu01** [comment]
The soft decision by ZLC was for the CLI squad to manage this contribution for now. @MikeBauerCA and Cartier have been in touch on this.

**Comment by solsu01** [comment]
@MarkAckert is this resolved or do we still need a vote? If so, how do we initiate a vote?

**Comment by MarkAckert** [comment]
We should log the contribution has been accepted in a zowe-zlc mailing list thread. I kicked off another thread to have the Zeepy repository scanned - once complete, we can migrate the repo into the Zowe org and close this issue.

**Comment by MarkAckert** [comment]
Contribution completed; closing.
