### ISSUE TITLE
Defining "Zowe Core" to be consistent in commercial Zowe Support Offerings

### ISSUE THREAD

**Issue by solsu01** [zowe/zac#170]
Broadcom and IBM both now have commercial support offerings for Zowe. For users to have clarity and avoid vendor lock-in, there should be consistency in what is called "Zowe Core" in these support offerings.

We need to define what is part of "Zowe Core" with respect to commercial support offerings.

**Comment by 1000TurquoisePogs** [comment]
@solsu01 correct me if I'm wrong but wasn't Broadcom's initial announcement about supporting what then was "all" of zowe? IBM's support I think is defined by what you can download from them?
So, at the moment it seems the de-facto "core" is somewhere between what you can download on zowe.org, and what you can download from IBM.

To me, this means that it excludes the repositories that we have but do not package, or package elsewhere such as npm.

What do you think?

**Comment by 1000TurquoisePogs** [comment]
Just something I mentioned on the ZLC call: if we go repo-by-repo, can we identify who strongly "owns"/knows the code in it? If we don't, is it "core"?

**Comment by armstro** [comment]
IBM distribution is determined by a few factors: 
1) what we make available for download, 
2) what we anticipate can be supported in partnership with the open community 
3) what can be supported in partnership with others (3rd parties, IBM product teams, etc.)  and 
4) what "front line" support resources we have to assist customers. 
The IBM Z Distribution for Zowe is on a continuous delivery model and therefore will likely expand as the factors above expand/change. 

Scope initially likely to be defined to be 
- All Zowe z/OS components including: ZSS, API ML, App Framework with "out of the box" apps (3270, VT, JES, USS, ...) 
- Zowe "core" CLI meaning the commands using z/OSMF plus the Secure Credential Store plug in. 
- Zowe Explorer 

IBM will continue to advocate for Zowe integrations by products teams in the open community. Support will be through the open community until such time as they are covered under IBM Support. 

**In addition to "defined code" there needs to be a way for that core set of binaries to be "trusted" (my word) by set of Support Providers - support vendors need a way to know each other distributions of Zowe core are unaltered.**

**Comment by jmertic** [comment]
Would this be linked to https://github.com/zowe/zlc/issues/182?

**Comment by armstro** [comment]
John - short answer is yes this is linked (there is also work going on to provide a way to test a given distribution of Zowe is "genuine" that is also related (that is in a different repo). 

We are beginning to try to use Zenhub to link and organize issues into Epics....there is a free zenhub plug in I am beginning to try to use (and will try to link cross repos).

**Comment by armstro** [comment]
The TSC will work the "what is core" question in this issue https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/issues/zowe/community/1207 ZLC will provide opinion for TSC consideration - I will summarize the ZLC discussion today in this issue. Core definition is part of the Support Conformance criteria and included in LTS scope description.
