### ISSUE TITLE
LTS go to market

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zac#176]
Issue to track LTS go to market

- **Done**  Publish the v1 conformance criteria in the OMP repo https://github.com/openmainframeproject/foundation/pull/9.   
- **Done** Publish LTS information in the Zowe documentation, tracked in https://github.com/zowe/zowe.github.io/pull/75.
- **Done** Publish PR https://github.com/zowe/zlc/pull/164 
- **Done** Customers coming to zowe conformance site are directed to v1 T&C and criteria
- Update Zowe conformance description on zowe.org to discuss 2019 and v1 conformance
- **Done** Update https://www.openmainframeproject.org/projects/zowe/conformance to discuss 2019 conformance program end and beginning of v1 conformance program
- Press release
- Blog on medium.com/zowe
- Social media posts on linkedin, twitter, ...

**Comment by RASakach** [comment]
Please add:

- Update Conformance Terms and Conditions to reflect V1 conformance program
- Update Conformance Criteria Check Lists (for all components) with V1 test criteria in new table format
- Update Conformance Program Participation Form to reflect V1 conformance for all components and to include valid links to Terms and Conditions and Test Criteria Check Lists
- Publish V1 conformance Marks
- Email existing conformant Extenders the V1 Test Criteria Check Lists in advance of official GTM

**Comment by RASakach** [comment]
Latest iteration of the Zowe LTS Roadmap
[Zowe.OSS.2019-20.Roadmap.Rev.16.chart.with.dates.and.conformance.pptx](https://github.com/zowe/zlc/files/4477984/Zowe.OSS.2019-20.Roadmap.Rev.16.chart.with.dates.and.conformance.pptx)

**Comment by jmertic** [comment]
Just seeing where we think this stands - want to get Mae engaged when everything is coming together.

**Comment by jmertic** [comment]
Talking with @Maemalynn, wanted to see where the expected press announcement stands. If the plan for the webinar upcoming is to focus on the LTS, it's probably good to have any press announcement at the same time.

**Comment by jmertic** [comment]
Did anything come together on the press release?

**Comment by Maemalynn** [comment]
@jmertic I'm not sure I understand your question or if this is even directed to me. But...Bruce and team filled out the questionnaire and put me in a great position to start drafting a press release. I'm in the process of drafting the release and reaching out to new Conformance Program members to see if they are ok with being a part of the news. In terms of priority, the webinar tomorrow will be part of the assets for this announcement, so I'm focused on that at the moment. Let me know if you have any questions.

**Comment by jmertic** [comment]
Thanks @Maemalynn - I guess I was asking broadly :-)

So it sounds like the press release will come some time after the webinar? For some reason I thought they were coming at the same time, but I must have misunderstood.

**Comment by Maemalynn** [comment]
@jmertic Our strategy changed as we're now seeing the webinar fatigue and registrant numbers aren't as high despite all of the promotion. So instead of going out the day of the webinar, we're including it as an asset that will help provide more details and visuals that will complement the release.

**Comment by jmertic** [comment]
Got it - that makes sense. Thank you!
