### ISSUE TITLE
Review of Zowe code backups 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#178]
In an internal meeting we briefly discussed the state of backup with github and learned releases are backed up but other extended/optional" code is not necessarily backed up - would we agree we need to have someone review the backup practices  and make recommendations. 

We know Marist agreement does not entitle the project to backups but they might accommodate snapshot backup of key environment.

**Comment by MarkAckert** [comment]
Do we have particular examples of the extended/optional code in mind? Is like the `community` repository, conformance guidelines, etc? Website, docs-site, other code materials not related to Zowe PAX or CLI Archive? All of the above 😄?

**Comment by armstro** [comment]
I would think we need to do an inventory first of what we have. (I had not 
even thought about website.) What I have heard is "Zowe Releases" are 
backed up ...but code not in "core" is not and that triggered by 
question..

Github? 
Website?
Doc? 
Samples? 
Build/test (Marist) - not incremental but "could" do a snapshot backup for 
point in time disaster recovery 
Automated Test cases? 
What does CII require? 

Item is to think about - know the gaps and decide if gaps need filled and 
how......


 
Bruce Armstrong 
IBM System Z Offering Manager- zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: armstrob@us.ibm.com
Tel: 919-254-8773
Cell: 919-931-3132

**Comment by MarkAckert** [comment]
Drafted our backup coverage here: https://github.com/zowe/zlc/blob/user/markackert/code-backups/tracking/Backups.md

**Comment by 1000TurquoisePogs** [comment]
Github recently did an archive and their explanation reveals that there are groups that backup github, so in effect there are multiple layers of protection on code that exists in github. https://archiveprogram.github.com/
By tagging the releases (we do), releases can be recreated from a github backup as long as the instructions are also present.
