### ISSUE TITLE
Agenda update for 09-05 zLC meeting

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zac#18]
**Open Source Needs - Discussion.**
_Can you add or merge this into the section please ?_  
When December zowe-1.0,pax is built this can only contain EPL 2.0 licensed content.  The current open beta zowe-0.9.0.pax has non EPL 2.0 licensed content which when removed means that none of the MVD desktop will function (as this uses zSS to authenticate to SAF).  The 3 explorers (JES, MVS, USS) will not function as these use WebSphere Liberty for z/OS 17.2.  The TN3270 and VT Terminal will not function as these use zSS.    Note that the editor squad is currently building out alternative editors using zSS that also will not be able to be included in the zowe-1.0.pax EPL 2.0 licensed.
Options.  1) Modify software stack so it includes EPL 2.0 compliant components in order to deliver its function.  2) Move more of the current software from IBM/Rocket license and ownership to zowe.org. 3) Provide a non EPL 2.0 licensed component that is a Zowe pre-req (similar to node) that includes the non EPL 2.0 licensed pieces.

_Other issues I'd like to see discussed._
**API mediation - SSO, API transformation, certificate trusting, ...**
In the process of onboarding tools and runtimes to the Zowe API mediation layer a number of issues have been identified that need addressing.  There is no current solution in Zowe for single sign on (SSO).  No-one is currently working on this as the ESM is not present so an alternative is needed.  

https:// certificate for the MVD server has expired
The current certificate self signed by Sean expired on March 2018.  Can we get a new certificate that isn't self signed and authorized by a trusted authority and replace this in the next build ?

Builds
The current build is a mixture of repositories from github.com/zowe and github.com/gizafoundation.  When will this switch over so we have a build that is fully sourced from zowe.org ?

**Comment by hogstrom** [comment]
MVD certificate has seem regenerated to expire in 2020

**Comment by hogstrom** [comment]
Issues here have been discussed in other issues and will be tracked independently.
