### ISSUE TITLE
MQ APIs listed on conformance page as CLI

### ISSUE THREAD

**Issue by solsu01** [zowe/zac#181]
Looks like an error:
![image](https://user-images.githubusercontent.com/35504644/79979357-67724600-846f-11ea-9db0-95cb9b0f35db.png)

**Comment by Joe-Winchester** [comment]
@solsu01 - yes it would be better if the text was "IBM MQ for z/OS" and the link was to the article https://community.ibm.com/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=adb8e2d4-f327-a93b-fdaa-b5da0e80d614&forceDialog=0 that describes how to surface the MQ APIs onto the API catalog which are valid for the 2019 conformance program

**Comment by Joe-Winchester** [comment]
@jmertic - is the Zowe Conformance web page in a github repo so Sujay and/or myself could create a PR for updating the text and links on the MQ CLI tile ?

**Comment by jmertic** [comment]
It is a GH repo - https://github.com/openmainframeproject/omp-landscape. Feel free to submit a PR for any changes needed.

**Comment by jmertic** [comment]
I will say that any links should point to an organization property ( i.e. with that having a Zowe logo, it should point to a Zowe/OMP location vs IBM )

**Comment by dkelosky** [comment]
This also seems like a problem for the App framework:
![image](https://user-images.githubusercontent.com/14940561/81570498-ab6db200-936e-11ea-89eb-2827f4e81790.png)

Are the IMS API & CLI conformant?  Should they appear there as well?

**Comment by jmertic** [comment]
For any additional apps needed, you should submit a conformance application so they are reviewed.

**Comment by dkelosky** [comment]
Thanks.  Since this is a Zowe repo based app - who would submit?  Is it typically the folks that seeded the repo?

**Comment by Joe-Winchester** [comment]
@dkelosky - I think it was the IBM MQ team who submitted the initial Zowe Conformance 2019 for the MQ CLI and MQ REST APIs.   @jmertic - I imagine they would have got an announcement e-mail for the Zowe Conformance v1 program when that went live a week or so ago ?  
For the IMS CLI and IMS Operations API we do want to get conformance for them also - I'll e-mail Haley and cc you as she will know more about whether that's in plan or not.

**Comment by Joe-Winchester** [comment]
Moving this issue to `/community` as it doesn't feel it is the ZLC responsibility to track this.

**Comment by jmertic** [comment]
@Joe-Winchester Yes - everyone who submitted for 2019 was contacted. Feel free to pass along that they can do ZOWE V1 conformance now if they missed the note.
