### ISSUE TITLE
PI Planning planning for 3Q2020

### ISSUE THREAD

**Issue by armstro** [zowe/zac#187]
- Name names of squad members for next PI (improve diversity on CLI, API ML and App framework squads) - separate issue for mentoring and diversity metrics 
- Agree on PI planning dates June 25, 26 and 29 (Thu, Fri, Mon)
- Put a plan in place for squad leads to provide their backlog items to be listed for consideration approx. 4-6 weeks before PI Planning dates 
- Survey the open community on their priorities ? 
- ZLC and squad leads to set general directions for PI 
- Establish process for public access to meetings without being disruptive 
- Establish agenda for June days (when is cross squad session, when squad only meet, playbacks,...)

**Comment by jmertic** [comment]
In terms of the question of balancing having public feedback vs avoiding disruption, wondering if having this be an initial kickoff of the TSC as well having those TSC members be the ones on audio and then others can contribute via chat.

**Comment by armstro** [comment]
Closing this issue as PI planning was completed - issue of communicating themes across squads also closed. Keeping the Diversity metrics issue open to still be addressed and TSC creation still needed and therefore left open
