### ISSUE TITLE
How to handle End of Support for Node.js V6 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#194]
Node V6 for z/OS is at "end of marketing" from IBM which means new copies of the code are no longer available. Customers are encouraged to move to Node V8 or V12. The Zowe system requirements document V6 or above as pre-req. How best to handle the phase out of V6. 
- Give notice to Zowe consumers via doc and or code messages? 
- Phase out of testing by CI/CD team 
Official end of support from IBM is Sept 2020. (The Node community has already dropped V6 and V8 support.) https://nodejs.org/en/about/releases/

**Comment by armstro** [comment]
Sean/Peter - My understanding is there are no know issues with V6 today and the question is what - if anything - the community should do or say as we know V6 will go out of support in Sept ....although customers are free to run unsupported if they choose.  I would like to discuss the following
- Introduce a warning message in the Zowe install scripts if V6 found - when to do this is up for debate (I would think at least 30 days prior to end of support). Knowing the pace of some enterprises software updates I would lobby for more days of warning 
- If (I stress if) you think it is worth stating something if a problem is found unique to V6 it will be addressed in V8 or V12. I think you said you did not want to code something specific to V6 at this stage of its life. The SMP/E format has a statement in Program Director that says V6 or higher. Zowe doc System Requirements also say V6 or higher 
https://docs.zowe.org/stable/user-guide/systemrequirements.html#common-z-os-system-requirements-host 

Or we say nothing - close this issue and take action once V6 is truly out of support.

**Comment by 1000TurquoisePogs** [comment]
Printing a warning sounds like a good idea. Due to current events, warning in advance is good.
But, I don't know what the warning will say. I see 3 options:

1 Warning, in september node 6 will not be supported by anyone, and therefore zowe's own support of it is best-effort.
2 ... and therefore zowe will not be accepting v6-specific bug fix requests
3 ... and therefore zowe will stop working with v6 soon after
How strong of a stance do we take? 3 gives us more freedom but isn't needed at this time. I think 2 is best.

**Comment by Joe-Winchester** [comment]
Issue https://github.com/zowe/zowe-install-packaging/issues/1410 exists to put a warning into the validate.sh script of Zowe that is used at startup to validate node.  This is option (2) that I agree with Sean is the approach we should take.  I don't want Zowe to stop working if a customer has node 6 - that would be punitive and I don't see what purpose it serves other than to drive traffic away from Zowe, but customers should be aware that they are working unsupported

**Comment by Joe-Winchester** [comment]
Doing a google of node support I find this https://developer.ibm.com/mainframe/2019/04/26/node-js-zos-v6-17/ that states:
```
As announced, the Node.js version 6 community release will hit end of life on 30 April 2019.   
IBM will continue to support paying clients of IBM SDK for Node.js – z/OS (based off of the 
Node.js V6 community release) past 30 April 2019
```
@armstro - where are the list of published dates for node ?  Is there a site that Roland and his team maintain ?

**Comment by armstro** [comment]
@Joe-Winchester to answer the EOS question see here: https://www.ibm.com/support/lifecycle/index.html#/details?q45=R736925B47749P13 Sept 30 2020 

Since we have warning messages in App framework and start up scripts for Zowe for Node V6 going EOS I will close this issue.
