### ISSUE TITLE
https://zowe.org/contribute/ needs a How to Submit a Defect page

### ISSUE THREAD

**Issue by phaumer** [zowe/zac#20]
People can contribute in all kinds of ways to an open source project. Contributing code is one way, but the far more common (and important one) is contributing Issues.  We need a page that provides guidelines on how to submit an issue. 

There  are currently 45 Repositories in github, so it is impossible for end-user to find the right place. This page should provide pointers to top-level repos or Squad-level planning repos to which to file the defects. It should also explain any other conventions and tags to use (e.g. for expressing severity).

Those top-level repositories to which people file their defects need to be monitored and the issue needs a reply and triage within a week to give the contributor their feeling that their feedback is valuable and has been heard and not lost somewhere.

**Comment by Tbr00ksy** [comment]
![Screen Shot 2018-09-27 at 12.24.12 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a907c3157b1d800120a86d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f46b7191a379ed0c2955415e4cbc21254d58eeb9cb74fce36f34985619e8836b5f73c63415a8b98b1fed07ba208a1cd1beea8e4495fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e94d53a1173162e27f3f6e0a.png)

Added a link for anyone to submit a general issue if they do not know which repo to submit to.

https://zowe.org/contribute/
