### ISSUE TITLE
Zowe Explorer logo

### ISSUE THREAD

**Issue by IgorCATech** [zowe/zac#202]
Recently I've been talking to John Mertic, asking for a Zowe Explorer logo that I could use in any related documentation. It turned out that there was no such logo yet. Here is a folder with existing Zowe logos https://github.com/openmainframeproject/artwork/tree/master/projects/zowe for your reference.
So, the idea is to have the Zowe Explorer logo created for documentation or/and marketing purposes.

**Comment by armstro** [comment]
Hey @IgorCATech - I don't think ZLC will be opposed to additional logos if you have worked through OMP (John Mertic). I think ZLC would like to comment on any new designs as more eyes reviewing can help. As I recall the designers of logos in OMP were spread thin and we had a few versions of the new logo but not a lot of "one offs" since the designers were spread thin. Is there a specific ask? or are you proceeding with OMP? When new logos proposed could you post pointer here?

**Comment by IgorCATech** [comment]
@armstro Thank you for your comment. Good to know about the situations with the OMP graphic designers. The last thing I want to do is overload them with more work. To answer your questions, there's no specific ask, it's just an idea. I haven't proceeded with OMP yet, and, frankly, I don't how exactly how to proceed. Write them an email? Open a GitHub issue? This is something I wanted to figure out by opening this GH issue :) So any direction will be much appreciated! 
PS: I would only create a design task if I knew the logo is used for multiple purposes - documentation, marketing, promo campaign, etc..

**Comment by armstro** [comment]
Apologies @IgorCATech - I get too much email and there are too many github issues - I guess my comments are 1) what is the issue with not using the current logos? Do they not fit well in documentation? or some other reason 2) I think having some proposed logo (even if not perfect) to submit for consideration would be helpful - the OMP owns the logos but I think the zlc could comment on what they like and don't like - we iterate a bit and then ask OMP for their view. The current logos were put up for a vote in the community so you might have a couple proposals and then the community have the final say.

**Comment by armstro** [comment]
@IgorCATech we discuss this issue briefly at the zlc today - we are unclear if you are asking for a very different logo for Explorer or a slight change to the existing logo (maybe different colors to show up better in the VS Code and/or documentation). We do not think it is wise to change the logo to be different than the rest of Zowe (if that is what you are proposing). You are welcome to bring ideas forward and we can decide what to do. (FYI to @solsu01 )

**Comment by armstro** [comment]
@IgorCATech wanted to touch base on whether this is still being worked?

**Comment by IgorCATech** [comment]
@armstro Thank you for reviving this issue. At some point, I've discussed this issue with my team and the consent was that we'll keep the Zowe logo for all Zowe components/subcomponents. I suppose this issue can be closed unless there are other suggestions.

**Comment by armstro** [comment]
Closing per Igor comment above
