### ISSUE TITLE
Improve summary of changes for each release

### ISSUE THREAD

**Issue by PeterFandelAtRocket** [zowe/zac#207]
The first section is probably meant to be high level summary of most important changes written more from perspective of benefit to persona.  However, this is not being consistently done to pull the most important changes from the various components.  Instead reader is left to read the nitty gritty details on a per github issue level. 

Better to have a consistent process for "promoting" a sub-set of detail-level changes individually and/or as groups to high level rel notes to appear in 1st section.

**Comment by armstro** [comment]
@PeterFandelAtRocket to check with @nannanli and @Joe-Winchester on what process is already in place for doc squad

**Comment by armstro** [comment]
@PeterFandelAtRocket were were concerns addressed in the 1.14 release to allow closing of this issue?

**Comment by PeterFandelAtRocket** [comment]
Problem solved!
