### ISSUE TITLE
We should define and publish our process on zowe.org

### ISSUE THREAD

**Issue by phaumer** [zowe/zac#21]
I propose to publish our development process or a link to a wiki with the process in the community page. External observers and people interested in downloading links are interested in process items such as 

- What is the general release road map
- What is the iteration schedule for new builds
- Where are the release notes / new and noteworthy for each release
- How to submit defects 
- How get defects triaged and how can I track progress on my issues

A really good example for such a process and wiki answering many question external parties and contributors have is here: https://github.com/Microsoft/vscode/wiki/Development-Process

**Comment by hogstrom** [comment]
@phaumer 
An update on this issue:

**What is the general release road map** - We are tracking 1.0 [here](https://github.com/zowe/zlc/issues/37))
**What is the iteration schedule for new builds** - it will be added to the website post 1.0 
**Where are the release notes / new and noteworthy for each release** - See first item.
**How to submit defects** - 
**How get defects triaged and how can I track progress on my issues** - https://zowe.org/contribute/
