### ISSUE TITLE
End of 3Q Zowe Update - OMP assistance 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#210]
Since not all topics for Zowe were covered at Share - proposal is to target a webinar in late 3Q to cover ZSS content that did not make Share plus content from 3Q development (HA, Containers, Security improvements, ...). Need to organize content - request OMP assistance.

**Comment by RASakach** [comment]
Thank you @armstro 
Will discuss at the next # Zowe Onboarding Squad meeting and will determine how best to move forward on a Zowe Webinar Series.

**Comment by RASakach** [comment]
The Onboarding Squad had Initial discussions on the Zowe Webinar Series and will be meeting with OMP to further plan.

Zowe Webinar Series Logistics:

- Plan to host 4 per year (1 per quarter)
- Kick-off the series in Q4 (Oct - Dec)
- If possible, keep the day of the month and time consistent (i.e. 2nd Weds of the middle month in the quarter, at 11:30am ET)
- Limit it to 45 minutes

 
Zowe Webinar Series Content:

- Highlight Topic (First one will be ZSS Content)
- General News
- PI Planning
- Other Community Events
- Reminder about (or results of) Surveys, Polls
- Squad News (single slide, very quick update/highlights)
- Customer(s) or New Onboarders Spotlight on Zowe Use / Zowe Extension
- Repeated Messaging with things like:  Want a Zowe Demo?  Want to contribute? Need an SME? GO HERE:

**Comment by RASakach** [comment]
@armstro I met with Chris B (OMP) today and we finalized plans for a quarterly (series) of OMP hosted Zowe Webinars.  Please review details with ZLC and let me know if we need to revise anything prior to finalizing.  

Details:
- Will Kick-off in October, tentative Wed Oct 14, 11:30 EST
- Will then reoccur 2nd Weds of the middle month in the next quarter (Feb 10th) --, 11:30 EST
- Will be limited to 45 minutes
- Will be recorded
- Will be able to conduct short polls / surveys during the meeting
- OMP will post to YouTube and can transcribe as a Blog Post
- Chris will add to OMP Webinar Calendar and will announce at OMS

Action Items:
1. Review the above details with the ZLC, identify any concerns (Bruce)
2. Review "Content" outline with the ZLC, identify any changes (Bruce)
3. Agree on Webinar Series Name: "Zowe Quarterly Meet-Up"?
5. Draft short summary of first meeting highlighted content and general meeting outline, send to Chris (see sample below)
6. Obtain "highlighted" speaker BIO, photo, and social media handles etc. (I believe this would be Joe Devlin from Rocket?)
7. Determine how best to notify the SQUADS (Slack Channels?) and obtain their "quarterly updates"
8. Determine who will "host" the series (perhaps this can be a rotating opportunity for each of the Squad Leads?)


Short Summary Draft:_
Zowe Quarterly Meet-Up:  Kickoff meeting
Introducing Quarterly Webinar Series for the Zowe Community!
Focus Topic:  ZSS [need more details here]
Focus Speaker:  Joe Devlin, Rocket Software 
Quarterly Updates include:
- General News
- Upcoming Community Events
- Squad News
- Recommended Resources

**Comment by armstro** [comment]
Thanks @RASakach for organizing this (sorry to be slow to reply).....I will put this on the ZLC agenda for next week (Aug 19) ......some thoughts: 

- To me quarterly is not often enough - hard to have a "cadence" quarterly. We should agree whether this is "education" or "marketing" and I lean to education. I think monthly is a better cadence assuming we agree this is education. 

- I question if 45 mins is enough time - - I realize it is hard for people to commit more time but I think 60 mins is needed.

- For the first session, we need to work with Joe Devlin to be sure this is workable for him. FYI - He was with Rocket but is now independent with his own company.  (His session is an example of why I am concerned whether 45 mins is enough. His topic plus kickoff the event and explain to the attendees what we want to do going forward)  I do think Joe's education is a unique opportunity for those that are interested in ZSS.  

- It might be good to preview topics for 2-3 meetings out even if they changed along the way but get people to "save the date" for future meetings - maybe ask each squad for a deep dive topic for future sessions. 

- One thing we might want to test is the OMP calendaring process - sometimes it works and sometimes not and I have never figured out a pattern - maybe we test with the zlc members or others and figure out how to get a calendar entry that works (and with the proper time zones) 

- I like the idea of doing a survey - we need to decide if a particular squad gets to author the questions or we mash together questions across squads. I assume we would use OMP Survey Monkey account - it worked well for PI planning. However, feedback was loud and clear the PI planning survey was too long (and it was estimated to be 15-18 mins of effort). 

So let's refine the "vision" a bit and get input from the squads - we will need everyone's help to make this a success.

**Comment by armstro** [comment]
Asking ZLC members for comments @PeterFandelAtRocket @1000TurquoisePogs @MarkAckert @Joe-Winchester @pdubz3

**Comment by pdubz3** [comment]
Lots to comment on ... 

I don't have a problem with quarterly.  These things take quite a bit of effort to do them right and make them successful.  If the turnout is overwhelming and the community gets great value, we can always explore increasing the frequency.

45 minutes can be short or long depending on what you have to say.  :-)  I wouldn't have any problem going to 60 minutes.  You don't want to go much longer than that, it gets harder for people to attend.

I agree that we should get a couple of meetings on the calendar ahead of time and possibly pre-plan and pre-announce the content for the next one if we know what we want to share in advance.  But I wouldn't go beyond the next session with pre-announcing, especially if we go quarterly.  There's no benefit to planning specific content for an hour-long session that's still six months in the future.

**Comment by pdubz3** [comment]
Sorry, that was quite rude of me.  :-)

**Comment by armstro** [comment]
Point taken on burden to set these up and provide content...goes back to agreeing on "vision" for these......in my mind it depends on how many people are sharing the workload - is this just the squads (who should be heads down on a sprint) or do we cast a wider net to include ISVs, customers, individuals like Joe D etc.........we can let others wade in......there was a prior "meet up" that I assume this could also include - more free form - but I was not able to attend so I don't have facts but heard favorable things.

**Comment by armstro** [comment]
Action from ZLC call today - Bruce reach out to Joe Devlin to get agreement on day and time.....Rose to confirm with OMP once agreement from Joe D. Need to know how much time Joe needs and flesh out the agenda (at a minimum do an intro to the quarter invites - maybe future topics - pointer to calendar, etc.) 

Try to get this firmed up by Aug 21 for OMP to include in OMP Summit news

**Comment by RASakach** [comment]
We need to get this to OMP very soon, (they wanted it today) - please let me know how you feel about this
Proposed Agenda:

- Quarterly Webinar Series Introduction
- Focus Topic:  ZSS & Zowe / Focus Speaker:  Joe Devlin
- Quarterly Zowe Update:  Zowe Squad Highlights and Upcoming Community Events

**Comment by Joe-Winchester** [comment]
+1 to your suggestion @RASakach .   It'd be great to also see if there was a way to involve Segus, and perhaps Phoenix, and customers, so we have external speakers (as you've done with Joe Devlin) going forward so there is a good balance between squad highlights and news, versus external customer/ISV stories.

**Comment by pdubz3** [comment]
I'm OK with this Rose, and I also agree with Joe's suggestion about external speakers going forward.  Have you gotten confirmation yet from Joe on his participation in the first webinar?

**Comment by RASakach** [comment]
Thanks for the feedback!

No confirmation from Joe Devlin yet.  I'll give it 1 more day.

+1 (@Joe-Winchester  comments) from me, we should definitely plan to feature Segus (hoping they will be V1 conformant by next quarterly meeting?) or Phoenix Software or a CUSTOMER for sure.  Perhaps one of them can summarize and "demo" an Extension?  Definitely want to have more focus on USERS with a sprinkling of "community happenings".   For the October Session, I think we will be just beyond Zowe PI Planning, but we should mention it, share highlights, and share tentative dates for Jan PI Planning.  @armstro  - assuming you will host the kickoff?

Also, Chris (OMP) would like to call the series:  "**Zowe Quarterly Update**"
And... she would like to setup a recurring meeting so that folks have it and keep it on their calendars.  Any objections?  Would we prefer to go with something a bit more casual that is not linked to a timeline like "**Zowe Meet-Up**"?    "**What's Up with Zowe?**"  "**Zowe Forum**", something else?

**Comment by armstro** [comment]
So I will "T" this up for discussion at Aug 26 ZLC call - I just sent Joe D a plea for title and abstract. 

I can host but anyone can - does not need to be me. 

I am flexible on what to call the quarterly "event" - putting on the calendar well is advance is ok with me. (We just need to deliver on content.) Based on the time it has taken to get this quarterly call going - I retract my ask to do monthly. If Joe D does not make this first session then I am fine with Segus or Phoenix (although we have already "tapped" Segus for Share session and I don't want to wear out our welcome). 

I am still going to ask if this is "education" or "marketing"? I asked Joe D for education (since we did not contain his topic in the Share sessions). We just need to be clear when we advertise the session. Ok to mix it up quarter to quarter. 

@RASakach we also mentioned doing a survey? We need to discuss how (if) we want to have one ready for this first session.

**Comment by RASakach** [comment]
As of 12:00 ET here's what we stand with an Agenda for our first Zowe Quarterly Update

2020Oct14  Agenda

1.   The Zowe Quarterly Webinar Series Overview  (Host, < 5 mins)
2.   Guest Speaker / Focus Topic (Guest Speaker, ~40 mins, +5 Q&A)
    -  Title:   Zowe & ZSS, Speaker:  Joe Devlin, ZOSS Team 
    -  Abstract:   Learn how we are extending the Zowe ZSS (z/OS back-end) to facilitate building in-depth (cross-memory, privileged, system-level) mainframe products with little-to-no assembler code required.
3.  Zowe Update: Zowe Squad Highlights (Host, 2 mins, single chart)
4.  Upcoming Community Events (Host, 2 mins, single chart)


Please let me know if OK to send to OMP ASAP!

**Comment by armstro** [comment]
Looks good - thanks for organizing this .....reminder we need to decide if we want to have a survey ready for this event too -

**Comment by RASakach** [comment]
@armstro FYI:  Chris Blum at OMP is finalizing details for the Oct 14 Zowe Quarterly Webinar.  Will need each of the Squads to produce a single slide on their "highlights" over the last quarter; could consider using the PI Achievements details.  As far as "promoting" the event, we should promote during PI planning and consider adding it to our ZOWE LANDING PAGE?  I've also asked Chris to promote via OMP.

**Comment by armstro** [comment]
Hey @RASakach - just email with @pdubz3 Mike regarding PI Achievements - I want to connect the two threads ....Mike wants a list for PI Planning and you need one for Oct 14....just want to be sure we don't ask the squad leads twice.......I am concerned about asking this late before Thursday and maybe use release notes on zowe.org to pull some line items for highlighting......we can discuss web page at ZLC meeting - I'm hoping it should be easy to do

**Comment by pdubz3** [comment]
@armstro @RASakach I just don't want it to be limited to new features.  For example, maybe we consider the fact that a new company has earned a conformance badge, or Zowe Explorer exceeding 17,000 downloads, things like that.  But the list of accomplishments we celebrate at PI Planning may not necessarily match exactly the list of highlights that Rose is asking about.  Or maybe it will.  Personally, I think completing the first community PI Planning for Zowe is a highlight for the quarterly webinar.  :-)  Anyway, I  emailed the squad leads and it shouldn't be too much for them to respond by tomorrow with a short list (no more than 2 or 3) accomplishments from their squad.  It shouldn't be a laundry list, that's not the point.  If I don't get the responses, we won't have a slide, or maybe we'll fall back on the release notes.  Either way the world won't end.

**Comment by RASakach** [comment]
@armstro @pdubz3 - apologies for the timeline confusion - we can gather what we want to present for the "Community Highlights" section of our Quarterly Webinar AFTER Zowe PI Planning - I just wanted to mention that item so that we can consider it / collect it at some point while we had similar work going on (for PI planning).    That said, if Mike is able to pull that collection from the Squad leads, that'll work.  :-)

**Comment by armstro** [comment]
Agreement at ZLC to close this item with the Q4 OMP Webinar on Zowe - a new issue will be opened for Q1 2021
