### ISSUE TITLE
Planning for Oct 1st and 2nd 2020 PI Planning 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#214]
PI planning date set of Oct 1&2 - 
- Organize working session with squad leads on 3Q accomplishments, new issues and items for 4Q 
- Does ZLC have any updated views on prior themes? 
        - Research on globalization? Sizing of effort
        - Increased focus on automated testing - include in code check in process? 
        - HA - status? 
        - PSI plans

**Comment by armstro** [comment]
[Zowe Community Context & Vision for 20PI3.pptx](https://github.com/zowe/zlc/files/5162028/Zowe.Community.Context.Vision.for.20PI3.pptx)

Prior deck - in need of update for 4Q PI Planning

**Comment by armstro** [comment]
[Zowe Community Context & Vision for 20PI4 Draft .pptx](https://github.com/zowe/zlc/files/5268003/Zowe.Community.Context.Vision.for.20PI4.Draft.pptx)

Draft deck for ZLC POV for 4Q - agenda topic for ZLC meeting today

**Comment by pdubz3** [comment]
@armstro Has anyone reached out to the squad leads to collect their notable achievements from the current PI yet?  Or did you have a different plan for building those achievement slides?

**Comment by armstro** [comment]
Hey Mike @pdubz3 - I have not reached out to the squad leads for achievements (a little late to do so in my mind) - I was think we have other topics to cover of higher priority - like TSC. I was going to highlight metrics, events (Share, OMP Summit, etc.).

**Comment by pdubz3** [comment]
@armstro It's definitely late but people like to see that leadership recognizes what they've accomplished.  Maybe it's not too late just to ask them each for a few (no more than 2 or 3) notable accomplishments to choose from that we can highlight on a single slide?   We don't need a whole slide from each squad I think a single slide works too.  If there's no time to present it then I guess we can do without.  Thoughts?

**Comment by armstro** [comment]
@pdubz3 I'm happy to have your help if you want to pull a slide together -

**Comment by armstro** [comment]
@pdubz3 even if you pull content from the release notes from zowe.org - it would be a way to collect info without reaching out to each squad lead

**Comment by pdubz3** [comment]
@armstro Absolutely Bruce.  I'll send an email to the squad leads right away requesting their short list of accomplishments, and if I get the responses I'll create a single slide for your deck.

**Comment by armstro** [comment]
[Zowe Community Context & Vision for 20PI4 Draft Sept 30 .pptx](https://github.com/zowe/zlc/files/5305320/Zowe.Community.Context.Vision.for.20PI4.Draft.Sept.30.pptx)

Draft of proposed deck for PI kickoff - to be discussed at ZLC meeting today

**Comment by pdubz3** [comment]
[Zowe.Community.Context.Vision.for.20PI4.Draft.Sept.30.pptx](https://github.com/zowe/zlc/files/5308288/Zowe.Community.Context.Vision.for.20PI4.Draft.Sept.30.pptx)

Updated the accomplishments section.

**Comment by armstro** [comment]
[Zowe Community Vision 20PI4 ZLC POV Final .pdf](https://github.com/zowe/zlc/files/5308580/Zowe.Community.Vision.20PI4.ZLC.POV.Final.pdf)

**Comment by armstro** [comment]
I would like to close this issue - if there are any follow up actions or lessons learned please created a new issue for the next PI Planning
