### ISSUE TITLE
Surveys for 20PI4 Planning

### ISSUE THREAD

**Issue by nkocsis** [zowe/zac#215]
Some squads have asked if we will have surveys ? If yes, then we might want to get some people involved to help ?

**Comment by armstro** [comment]
Nick - I would turn this around - what squads have survey questions? What questions are they? are they critical for 4Q? ZLC is not against doing a survey but we need to give lead time to get it composed and get replies. Another options is Zowe is planning a quarterly "event" - first one is targeted for Oct 14 and the PROPOSAL is to offer a survey then ....... and do a quarterly cadence.

**Comment by RASakach** [comment]
+1 from me on.... understanding which squads have questions.  I would also suggest having the squads move forward with planning and while doing so, as questions come up, consider adding them to a survey that we will MARKET and ENCOURAGE PARTICIPATING in during our Quarterly Webinar.  I realize we will be 2 weeks in to the PI but getting feedback is a fluid activity.  If we can get folks in the "groove" of expecting 1 survey per quarter, that we will announce during our webinars, it would work out for all.   Anything needed in advance can be posted via SLACK channels right?

**Comment by armstro** [comment]
ZLC opinion is to survey twice a year in Jan and July ....I recommended closing this item BUT placing the reminder on the development calendar to prep for Jan survey
