### ISSUE TITLE
Plan Q1 2021 OMP Zowe Webinar

### ISSUE THREAD

**Issue by armstro** [zowe/zac#217]
See https://github.com/zowe/zlc/issues/210 for context

**Comment by armstro** [comment]
January is proposed month for Zowe survey to the consumers - one agenda topic to be considered

**Comment by RASakach** [comment]
Zowe Quarterly Webinar Details so far:

Date:  January 20, 2021 at 1130 ET
Registration Link: https://bit.ly/3mbTAwq

Highlight Topic:  TBD
Highlight Squad:  Proposing DOC SQUAD to review Website Updates?

General News:
Zowe Survey [overview, where to find it? etc.]
PI Planning
Other Community Events
Polls
Customer(s) or New Onboarders Spotlight

**Comment by armstro** [comment]
Close - many thanks to @RASakach for getting meeting organized
