### ISSUE TITLE
Vendor neutral zCX, Open Shift, Sysplex, test environment for Docker images needed 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#218]
For 1Q21 a vendor neutral zCX test environment is needed for Docker images - Vicom has offered but their environment would be a loan - we need to work with OMP and/or OMP members for a publicly accessible test environment.

**Comment by armstro** [comment]
I've expanded the scope here and I think this needs to be a ZLC item in cooperation with System Squad and OMP.

**Comment by PeterFandelAtRocket** [comment]
Now an OMP project to get Z resources...
