### ISSUE TITLE
Future ZLC structure 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#220]
Two factors driving a rethink of the ZLC 1) term limits expiring for some ZLC members in Feb 2021 2) formation of TSC - assuming it is approved. https://github.com/zowe/zlc 
Existing ZLC mission needs rethought as technical issues will be more the domain of the TSC. Assuming ZLC retains its more "business focus" priorities need to be set - possible closer work with OMP, reach out activities, incubators, more focus on new members, etc. 
This item is to work out mission of ZLC for 2021

**Comment by armstro** [comment]
In reviewing the ZLC description on zowe.org https://github.com/zowe/zlc it states a few things in need of update 
- Mentions voting on "sub-projects" which has evolved to mean "incubators" (I think) 
- Says we work with OMP marketing (which we do to some extent and needs to continue/enhanced) 
- Says to create and maintain "release train" which I assume is how we have gotten into the voting for release approval 
- And says we vote to revoke committer privileges (if needed) 

I would like to propose with TSC creation we continue to approve incubators, work with OMP in not just marketing but recruiting new members and projects, work to outreach to other projects and any other ideas we want to document. I consider "release train" issues the scope of the TSC and should maybe also be the ones to revoke committer authority. 

Regarding ZLC members and voting 
- I propose the 3 "technical" ZLC members that move to the TSC focus on the TSC and not do "double duty" between TSC and ZLC
- I think whoever the TSC chair is becomes a voting member of the ZLC (that person does do double duty and bridge between the "business" and "technical" bodies
- I propose the ZLC stay a 6 seats (no more than 2 from the same company) but we seek out new members to the ZLC to increase the diversity even if that means some seats go unfilled for a period of time as we find members 

We can discuss in January but wanted to document some of the ideas here.

**Comment by armstro** [comment]
Addition topic: term limits - also see on the zowe.org site: 
1 Year Term ending February 26th 2021:
Bruce Armstrong, Sujay Solomon (passed control to Mike D), Peter Fandel
2 Year Term ending February 26th 2022:
Mark Ackert, Sean Grady, Joe Winchester

Note the members moving to TSC term limit in 2022 - those of use staying on ZLC have term limit of Feb 2021.....we need to discuss (and seek @jmertic advice on how to handle) ......do we vote for all new ZLC members (allowing current members to run again) or some other arrangement?

**Comment by armstro** [comment]
Adding comments from ZLC meeting on Jan 6th

- Charter of ZLC be adjusted (keep incubator approval, and themes/hills for PI Planning, add more work with 
OMP - events, marketing, partnerships with other projects). 
- This charter to be done in cooperation with TSC to avoid overlap. Policy on active members (for example) and creation on new projects/new repo (code contrib but not part of build). 
- Seek for diversity 
- New area for consideration is planning open community "infrastructure" needs - for example there is need for zCX, Sysplex, OpenShift environments not currently being met and need to work with OMP and System Team on how to address

**Comment by armstro** [comment]
[Zowe ZLC proposal 2021 Draft .pptx](https://github.com/zowe/zlc/files/5842228/Zowe.ZLC.proposal.2021.Draft.pptx)

These slides are proposed modifications to the ZLC charter on the zowe.org web site

**Comment by armstro** [comment]
Keeping proposals open for review - PR proposed by Bruce is here https://github.com/zowe/zlc/tree/armstro-patch-4 

Peter proposal 

[ZAC Rewrite by Peter.docx](https://github.com/zowe/zlc/files/6076091/ZAC.Rewrite.by.Peter.docx)

Bruce comments 
[ZAC Rewrite by Peter BA mods.docx](https://github.com/zowe/zlc/files/6076092/ZAC.Rewrite.by.Peter.BA.mods.docx)

@pdubz3 to review/comment

**Comment by jmertic** [comment]
Adding my thoughts - please loop me in on the next call on this...

[ZAC.Rewrite.by.Peter.BA.mods with JM comments.docx](https://github.com/zowe/zlc/files/6076662/ZAC.Rewrite.by.Peter.BA.mods.with.JM.comments.docx)

**Comment by armstro** [comment]
[ZAC Draft Charter - Consolidated Comments .docx](https://github.com/zowe/zlc/files/6080339/ZAC.Draft.Charter.-.Consolidated.Comments.docx)
OK - we are getting close - I took most to Mike's edits to condense the verbiage. I replied to John's comments - I think the biggest area of disconnect is regarding ZAC approving incubator projects. 

Mike offered some times for working session - I am going to pick a hour that he and I have free and see if all can join

**Comment by armstro** [comment]
Just a thought - I think there is agreement that ZLC/ZAC needs to "own" the issue for Zowe Support Conformance program (granted it could be a TSC item but ZLC/ZAC seems a fit) - I would like to dissect the issue as to why this issue is appropriate for ZLC/ZAC and use it as a case study ...I think it is a role beyond "advisory" to TSC .....is it the "business aspect" of conformance? the fact we already have 2 vendors offering support in the ZLC/ZAC ...

**Comment by pdubz3** [comment]
Bruce, I think conformance for support offerings and distributions would ultimately be a joint effort.  It involves the business aspect of creating the enterprise-grade experience for Zowe customers as well as the rules of engagement for support vendors which I believe to be non-technical details and within the domain of the ZAC.  It also touches the specific details of the Zowe deliverables and how Zowe is acquired, installed, configured and maintained.  The fact that we have two vendors already offering support shouldn't be relevant to the definition of conformance, although it's reasonable that it might influence some opinions.

Having said that, it needs to be owned by one, not both.  And I feel the ZAC is the appropriate owner.

**Comment by jmertic** [comment]
Seeing where this is at - I see the ZLC right now operating with good intentions, but without a solid swimlane. Let me know what I can do to help drive this forward.

I recall the last discussions were transitioning the ZLC to more of a 'vendor advisory group' with participation driven by organizations with Zowe Conformant offerings and its role to advise the TSC and being a resource for the TSC in ensuring the project is in line with its downstream vendor ecosystem. I like @pdubz3 idea of letting this group be tasked with coordinating the establishment and evolution of the conformance program criteria for the TSC to approve - likely this group will be the right target audience.

**Comment by armstro** [comment]
John - we want to close on the Support Conformance first and then revisit 
the charter.....PI Planning and Incubators took up time in 1Q..... the TSC 
has (I think) settled on their charter and there are a few things they ask 
of the ZLC/ZAC that we need to sort out......
 
 
Bruce Armstrong 
IBM Z Product Manager assigned to  zowe.org 
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: ***@***.***
Tel: 919-254-8773
Cell: 919-931-3132


                       



From:   John Mertic ***@***.***>
To:     zowe/zlc ***@***.***>
Cc:     Bruce Armstrong ***@***.***>, Assign 
***@***.***>
Date:   05/24/2021 10:55 AM
Subject:        [EXTERNAL] Re: [zowe/zlc] Future ZLC structure  (#220)



Seeing where this is at - I see the ZLC right now operating with good 
intentions, but without a solid swimlane. Let me know what I can do to 
help drive this forward. I recall the last discussions were transitioning 
the ZLC to more of a 'vendor 
Seeing where this is at - I see the ZLC right now operating with good 
intentions, but without a solid swimlane. Let me know what I can do to 
help drive this forward.
I recall the last discussions were transitioning the ZLC to more of a 
'vendor advisory group' with participation driven by organizations with 
Zowe Conformant offerings and its role to advise the TSC and being a 
resource for the TSC in ensuring the project is in line with its 
downstream vendor ecosystem. I like @pdubz3 idea of letting this group be 
tasked with coordinating the establishment and evolution of the 
conformance program criteria for the TSC to approve - likely this group 
will be the right target audience.

**Comment by armstro** [comment]
OK - let's try to reboot the charter discussion - I think we start here to recall what is already out there 
https://github.com/zowe/zlc  

I think we need to read TSC charter for positioning of ZLC/ZAC role 
https://github.com/zowe/community/blob/master/Technical-Steering-Committee/charter.md 

We can discuss the word doc (I don't think a PR has been started)...

[ZAC Draft Charter - Consolidated Comments Reboot Jun 18 .docx](https://github.com/zowe/zlc/files/6677650/ZAC.Draft.Charter.-.Consolidated.Comments.Reboot.Jun.18.docx)

1) Do we REALLY want to rename ZLC - I would rather not do we REALLY Lead or Advise? Philosophical debate. 
2) I think there is general agreement we approve incubators that take the project in a new direction - and we owe the community the criteria used to approve an incubator proposal 
3) I think we advise on "core" but TSC decides 
4) We can seek out from the TSC what they want from ZLC/ZAC

**Comment by armstro** [comment]
Document attached is merge of the existing TSC charter, Contributor File with roles (for reference) and CNCF Principles to be considered for Zowe principles 

Possible areas for ZLC (ZAC) to serve as **advisors**
- Summary of requirements/feedback from stakeholders (Member vendors, customers/consumers/extenders, ISVs, GSIs, Academic users, ...) 
- Future hills based on indicators of market needs 
- Metrics for measuring the project acceptance/progress 
- New version considerations 
- New conformance criteria considerations 
- Releases MVP 
- Core contents/definition  
- Guiding principles to be considered  
- New member recruitment 
- Projects/incubators maturity 
- Maintaining vendor neutral policy (or documenting exception conditions since z/OS environment is not vendor neutral) 

[TSC Charter + Contributor File + CNCF Principles.docx](https://github.com/zowe/zlc/files/6729835/TSC.Charter.%2B.Contributor.File.%2B.CNCF.Principles.docx)

**Comment by armstro** [comment]
[ZAC.Draft.Charter - July 19 2021 .docx](https://github.com/zowe/zlc/files/6843072/ZAC.Draft.Charter.-.July.19.2021.docx)

Much simpler ZAC Charter - topic for July 20 ZLC/ZAC call

**Comment by armstro** [comment]
[2021.July.Zowe.Quarterly.Webinar.Series.ZAC Overview .pptx](https://github.com/zowe/zlc/files/6848064/2021.July.Zowe.Quarterly.Webinar.Series.ZAC.Overview.pptx)

Proposed summary of ZAC

**Comment by armstro** [comment]
[ZAC.Draft.Charter - July 20 2021 .docx](https://github.com/zowe/zlc/files/6848301/ZAC.Draft.Charter.-.July.20.2021.docx)

Incorporating comments

**Comment by armstro** [comment]
@jmertic above is proposed ZAC charter - question is what - if anything - do we need to do to sunset ZLC charter and related zowe.org content?

**Comment by jmertic** [comment]
Thanks Bruce - I'm reading the charter and struggling a bit with the concept of an "advisory" group having specific responsibilities or "owning" activities. I would have anticipated this group similar to a [customer advisory council](https://en.wikipedia.org/wiki/Customer_advisory_council), which would be easy to convey as a model to the mainframe community and add more clear direction/focus. Happy to chat through this more.

**Comment by armstro** [comment]
Hey @jmertic - I think you had asked where we were with the ZAC charter - I provided you this github info - let us finalize the proposal - it likely needs a little clean up and simplification. 

The "owning" activities is meaning action items assigned by TSC but maybe the word "owning" is not right term or we just need to say action items as agreed. We also need to figure out what to do with the zowe.org contents - there is a fair amount of content that is ZLC specific we need to remove and bridge to a simpler ZAC description. 

What do we need to do about changing the charter of ZLC to ZAC ? Is it necessary to vote on anything - either by the ZLC or the community at large?

**Comment by jmertic** [comment]
Got it - didn't realize the charter was still at an early stage. 

Transition-wise, I think messaging to the community on the transition should be sufficient; it might be good to have the TSC review and approve the plan for the ZAC as well.

**Comment by PeterFandelAtRocket** [comment]
I made another version to address John's concerns and attach two copies - one showing what I changed and the other with all changes accepted.
[ZAC.Draft.Charter.-.August.3.2021-visible-edits.docx](https://github.com/zowe/zlc/files/6925255/ZAC.Draft.Charter.-.August.3.2021-visible-edits.docx)
[ZAC.Draft.Charter.-.August.3.2021.docx](https://github.com/zowe/zlc/files/6925257/ZAC.Draft.Charter.-.August.3.2021.docx)

**Comment by pdubz3** [comment]
Peter, I reviewed your edits and they're good.  I corrected two errors, one grammatical and one spelling (a typo).  
[ZAC.Draft.Charter.-.August.3.2021.docx](https://github.com/zowe/zlc/files/6925573/ZAC.Draft.Charter.-.August.3.2021.docx)

**Comment by jmertic** [comment]
What is the state of this document? I had lots of feedback but want to be conscious of where things are at.

**Comment by armstro** [comment]
I will ask in the ZLC/ZAC call today - I think we are done - next step is ask TSC to approve. We need to figure out how to update the zowe.org website - there are many references to ZLC .....I propose we provide an explanation of the name and mission change and strip out all the rest

**Comment by jmertic** [comment]
Got it - can we schedule time this week to walk through this more?

**Comment by armstro** [comment]
Forgive me - I felt the need to beat the horse but a little bit more 

1) Softened the Product Management comment a little tiny bit to "The ZAC brings a product management perspective to the community and acts in cooperation with the others Zowe squads such as the Zowe Technical Steering Committee (TSC) and the Zowe Onboarding squad."   

2) Added sub-bullet to explain "hill" (with link to SAFe methodology) in response to concern about being an insider term 

3) Gave a few more words on Chair, Vice and Secretary 

I'd like to take this to TSC for approval and we work with TSC on updating zowe.org. To stress the role of "advisory" I will try to use the full term externally and try not to just say ZAC. 

DONE 

[ZAC.Draft.Charter.-.August.18.2021.docx](https://github.com/zowe/zlc/files/7010843/ZAC.Draft.Charter.-.August.18.2021.docx)

**Comment by PeterFandelAtRocket** [comment]
I think your new language is just right

**Comment by PeterFandelAtRocket** [comment]
ZLC dead. Long live ZAC!

**Comment by PeterFandelAtRocket** [comment]
done
