### ISSUE TITLE
Should Zowe adopt ICLA as replace for DCO process (if possible) 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#222]
IBM has 5-7 new deverlopers joining various squads. These are members of an team we refer to as Jump Start - they earn credit/badge for open source contributions. They are not full time on Zowe - this is in addition to their day job. 

One "process issue" we should decide is whether Zoew/OMP want to put in place a ICLA from the developers as their signed assertion of the originality of their commits as being their own and save scanned images of those documents in the zlc or another OMP archive. We use that as the legal basis for their signoff and we turn off DCO.  The gate is no one is allowed access without a signed ICLA (Individual Contributor License Agreement). It would make the process less tedious and achieve the legal requirements we are looking for.

**Comment by armstro** [comment]
Hey @jmertic - we (IBM) are likely to have another batch of new hires be briefed on Zowe for them to earn "first contributor" badge as part of their developer education. 

The people running the education have an Apache background where - I am told - ICLA are used. The new hires are told to seek out the ICLA if they chose Zowe as their open source community to contribute - this causes some confusion when we explain it does not apply to the project - does ICLA make sense for Zowe in the future? Is there another process planned by LF? 

I can make the new hires aware of LF policy but wondering if there are changes on the horizon? For 2Q might be too near term change - I am wondering for 2H2021? We are likely to have new hires considering Zowe on a quarterly basis this year. @Joe-Winchester

**Comment by jmertic** [comment]
Right now the Zowe Charter has aligned on the use of the DCO for contributions. It sounds like part of the concern could be messaging and tooling, both things outlined to some degree at https://github.com/openmainframeproject/tac/blob/main/process/contribution_guidelines.md but things I'd be happy to help with improvements in the Zowe documentation. Let me know if this could help

**Comment by armstro** [comment]
Closing as the Zowe squads have some tooling now to prevent the DCO problems of the past.  ICLA was requested by new contributors to Zowe that were not aware of the DCO process and ran into problems.
