### ISSUE TITLE
Zowe Certification testing as part of Zowe Conformance 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#225]
Zowe Conformance criteria today consists of vendors identifying the active contributors to the squads with no real indication of skills of the individuals. This issue is to establish certification test criteria for the future as a measure of skills aptitude. Example to research is Kubernetes certification.

**Comment by PeterFandelAtRocket** [comment]
Zowe support conformance program has been put in place.  This may be eventually desired but will be handled by the TSC after v2 comes out
