### ISSUE TITLE
Coordinate SHARE submissions Oct 5 deadline

### ISSUE THREAD

**Issue by armstro** [zowe/zac#23]
Should broadcast deadline to squads and early adopters. Coordinate content tailored for each track (feedback was last SHARE had several repeats of content - understandable as first time)

**Comment by hogstrom** [comment]
I'd like to assign an owner to this action.  Volunteers?

**Comment by jmertic** [comment]
Mae can help coordinate submitting submissions - let's work through her so we are tracking this.

**Comment by jmertic** [comment]
Let's also invite Mae to this waffle for items to coordinate with the marketing committee.
