### ISSUE TITLE
Blog Explaining ZLC to ZAC 

### ISSUE THREAD

**Issue by armstro** [zowe/zac#230]
As we work with the TSC on Zowe.org changes we should have a blog to explain the ZLC to ZAC transition - some ideas: 

- One thing fun about open source is the freedom to change and adapt. 
- The community formed the TSC earlier this year and it is now well established. 
- Zowe is a collection of teams (we call squads) and the TSC is made up on squad leaders who work cross squad to advance Zowe. 
- We saw the need for the TSC to speed technical implementation - we've seen great progress in on time deliveries of releases and more rigor in the dev process. 
- Many capabilities in Zowe require cross squad coordination and the TSC is there to make that happen. 
- Open source has a history of developer lead innovation. The TSC aligns with many open source project. 
- Great developers know they can't code and listen to the market simultaneously. 
- Listening and advising is now the role of the Zowe Advisory Council. 
- Open to all - intended to the voice of Zowe consumers and stakeholders.

**Comment by PeterFandelAtRocket** [comment]
Thanks for creating this issue Bruce.  I took the action item from our last ZAC meeting to kick this off with a draft document we can all start contributing to collectively, and went ahead and wrote the attached draft before noting that you had written the above bullets.  So please do not take my draft's omission of those bullets as a rejection of them.  I just ran out of Zowe time today
[Who is Zack.docx](https://github.com/zowe/zac/files/7227753/Who.is.Zack.docx)
!

**Comment by pdubz3** [comment]
Peter, excellent start.  I've reviewed the existing content and made a few suggestions as comments (attached here).
[Who.is.Zack.docx](https://github.com/zowe/zac/files/7228219/Who.is.Zack.docx)

**Comment by armstro** [comment]
One observation - maybe some acknowledgement needed of TSC operating under the policies and practices of the Linux Foundation to explain the project is part of a bigger org? 

Some words off the top of my head: 

ZAC membership and governance

The Zac is open to all interested parties of Zowe's future. It is a group to focus on "what to build next" for the good of the z/OS platform. Your participation can be in live meetings (put link to the calendar) or by raising issues for consideration (put link to github). Like any Product Management and Development relationship the more fact-based case to make to assist with work prioritization the better! The ZAC is intended to run on a consensus basis - there is no voting process involved. The group's purpose is to describe the needs of the consumers of Zowe in a way to provide the TSC clear objectives for future releases. Come join the ZAC team and assist in shaping the future of Zowe.

**Comment by PeterFandelAtRocket** [comment]
With this new version I have incorporated all feedback thus far provided   ...hopefully to satisfaction.

[Who.is.Zack.docx](https://github.com/zowe/zac/files/7267567/Who.is.Zack.docx)

**Comment by PeterFandelAtRocket** [comment]
New version
[Who.is.Zack oct12.docx](https://github.com/zowe/zac/files/7341002/Who.is.Zack.oct12.docx)

**Comment by armstro** [comment]
[Who.is.Zack.oct12 - update for 2023.docx](https://github.com/zowe/zac/files/11463628/Who.is.Zack.oct12.-.update.for.2023.docx)

**Comment by PWFlyMan** [comment]
@armstro Test comment.

**Comment by armstro** [comment]
Although I can assign this @PWFlyMan there are other github issues that I try to assign you and your name does not appear as a valid option

**Comment by PWFlyMan** [comment]
> Although I can assign this @PWFlyMan there are other github issues that I try to assign you and your name does not appear as a valid option

Do I need to be set as a Collaborator?

**Comment by pdubz3** [comment]
Bruce, I turned on tracking and made some suggestions in the attached, including a stab a new title that might serve as click-bait for mainframe leaders who like to get involved, even if they don't know what ZAC is.  
[Who.is.Zack.oct12.-.update.for.2023 (1).docx](https://github.com/zowe/zac/files/11510476/Who.is.Zack.oct12.-.update.for.2023.1.docx)

**Comment by Domenico-DAlterio** [comment]
I reviewed the document and I don't have specific comments, thank you

**Comment by armstro** [comment]
Medium darft here https://medium.com/@armstrob/seeking-leaders-to-help-shape-the-future-of-the-mainframe-using-open-source-573bc3c6f0c2 

Need some help with ideas for images to include? How to be sure to file as Zowe Vendor Neutral category and to get the review process going

**Comment by armstro** [comment]
Blog submitted to medium.com and reviewed - publication pending
