### ISSUE TITLE
Create training for Zowe Administrators and Developers

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#238]
As Zowe is now stabilizing down, the next logical step is to drive a community built Zowe Adminstrator and Zowe Developer training, along with a certification, that will help grow the market and enable customers and vendors.

Kubernetes is a great pattern to follow:

https://training.linuxfoundation.org/?s=kubernetes&filter=certification
https://training.linuxfoundation.org/?s=kubernetes&filter=training

If we could have SMEs from the community, we can pattern with LF Training on delivery

**Comment by armstro** [comment]
Duplicate item from Onboarding - closing - work continues on OMP Z box - exploration with Interskill for pilot of API ML course
