### ISSUE TITLE
Transfer zowe.org domain name and website to LF IT

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#29]
Need to get this moved over sooner than later. Would be good to get website settled down for LF CS to review ASAP.

**Comment by hogstrom** [comment]
Does this mean domain transfer or the website?   I'm concerned about moving the website because when we suggest changes the answer is generally talk to an LF comittee for updates and I'm worried we'll get locked out; whether thats true or not, it seems like a real possibility .... I'd like to have the process outlined and agreed to before moving the site.

**Comment by jmertic** [comment]
Both - and we can work out a process that works for all parties. But these
does need to be done.


-- 
John Mertic
jmertic@gmail.com | http://jmertic.wordpress.com

**Comment by hogstrom** [comment]
And they will be after you identify the process.  As I said, I’m not comfortable with the current approach which is effectively blocking progress, not enabling it.

**Comment by hogstrom** [comment]
Here is my strawman

The Zowe Community owns the Wordpress blog, access to the underlying system it is hosted on and can manage content without going through a comittee.  

New systems can be added to the domain and we own the naming of the systems.

I'd also like to understand the process, timeframes, etc.  Right now the systems have access via VPN to certain resources that will get moved when VCU goes live but need access by known individuals.

I know this s complicated but a conversation and document outlining the committments is needed.

**Comment by jmertic** [comment]
Good start - here's my thoughts:

- I think content-wise it makes complete sense for named individuals on the project to have edit access and the ability to create new pages ( frankly speaking, the Zowe team is the SMEs for the content there ). We deploy 'Salient Visual Composer' on sites to make it easy to do this for the community without having to get CS involved most of the time.
- I'm a bit confused on 'access to the underlying system it is hosted on' - what are you specifically looking for?
- 'New systems can be added to the domain and we own the naming of the systems.' - can you elaborate on your expectations here? I'm thinking this is related to the planned build/CI infrastructure, which I would anticipate the community would be primarily engaged and involved on.
- Timeframe for domain and website transfer should start ASAP. I can get LF IT engaged on this specifically when you are comfortable with this.

**Comment by hogstrom** [comment]
- I'll look at Salient ... I'm not familiar with it.
- In terms of access, we've written some scripts that work with Apache to gather download statistics, copying files, positioning them for download, etc.  We also installed ZDT which requires VPN access to a license server ... hopefully this is a short term issue but will likely persist until we have a viable alternative like VCU up and running.  One option is to leave river.zowe.org in place until we establish the alternate z/OS environment.
- In terms of naming, we are naming the servers in a theme from Firefly.  River, Jayne, Wash, etc.  Perhaps the best way of doing this in a staged manner is to move wordpress and the domain to LF and continue to use the servers that have security restrictions until VCU comes up.
- I assume that the LF has a way to access our Wordpress and move it ?

**Comment by jmertic** [comment]
_I'll look at Salient ... I'm not familiar with it._

+1

_In terms of access, we've written some scripts that work with Apache to gather download statistics, copying files, positioning them for download, etc. We also installed ZDT which requires VPN access to a license server ... hopefully this is a short term issue but will likely persist until we have a viable alternative like VCU up and running. One option is to leave river.zowe.org in place until we establish the alternate z/OS environment._

Let's ensure this is considered in the build infrastructure build out. My gut says these boxes will need to be reviewed and transitioned one by one.

_In terms of naming, we are naming the servers in a theme from Firefly. River, Jayne, Wash, etc._

Fine by us - we have no naming opinions  ;-)

 _Perhaps the best way of doing this in a staged manner is to move wordpress and the domain to LF and continue to use the servers that have security restrictions until VCU comes up._

Yes, let's deal the website and domain name ownership first since those are trivial and then bring the other items over as the build infrastructure comes up. Sorta what I had in mind.

_I assume that the LF has a way to access our Wordpress and move it ?_

Likely yes, but we'd need our team to review and scope to see if there is any problematic plugins or other concerns that would add complexity. Also would want to ensure the site could be in a relatively stable state to reduce the make-work.

**Comment by hogstrom** [comment]
Transfer initiated to LF.   Waiting for comms back from LF

**Comment by hogstrom** [comment]
Complete
