### ISSUE TITLE
Open Source Development Metrics

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#3]
Can we look into using a tool like [Grimoire Lab](https://chaoss.community/software/) to help us assess the health of our community?

**Comment by hogstrom** [comment]
This looks really interesting.  Do you have familiarity in setting it up and using it ?

Matt Hogstrom
matt@hogstrom.org
+1-919-656-0564
PGP Key: 0x90ECB270
Facebook <https://facebook.com/matt.hogstrom>  LinkedIn <https://linkedin/in/mhogstrom>  Twitter <https://twitter.com/hogstrom>

“It may be cognitive, but, it ain’t intuitive."
— Hogstrom

**Comment by hogstrom** [comment]
Any owners for this one ?  If not, I'd like to archive this and address when it comes up again.

**Comment by hogstrom** [comment]
Will create a post GA milestone to revisit this item.

**Comment by jackjia-ibm** [comment]
We have a Grimoire Lab service launched. Please contact me or Tim Brooks for details if you want to reach the data.

**Comment by jackjia-ibm** [comment]
Grimoire Lab default configuration is too aggressive and caused 2 issues:

- consumed GitHub API calls too fast and reached quota limitation, which blocks others to make GitHub API calls,
- the default logging is DEBUG level and used 20G per day for logging.

The service is temporarily shutdown until I figure out a way to configure it.

**Comment by jmertic** [comment]
Two things here...

- Would it make sense to use this ticket to align on the metrics of interest to the project?
- Once that is aligned, I'd suggest having a service offering through Bitgeria that would we could manage here. This would free up the current team which is likely quite busy in pulling the releases together.

Thoughts?

**Comment by jmertic** [comment]
The team at Bitergia put together a quick dashboard for review at http://cauldron.io/dashboards/zowe. Hopefully this gives the group a good idea of what's possible, and they are able to add into Slack and the mailing lists ( potentially also downloads of the binary ) to complete things out if folks are generally happy with the solution.

**Comment by hogstrom** [comment]
Closing ... as issues that require ZLC awareness arise new issues will be opened.
