### ISSUE TITLE
Work with VCU on capstone program.

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#30]
Bob Dahlberg is putting something together - will attach proposal. Would be good for ZLC to comment and determine who could mentor.

**Comment by jmertic** [comment]
[CS 305 - Dahlberg - OMLF Zowe.docx](https://github.com/zowe/zlc/files/2380621/CS.305.-.Dahlberg.-.OMLF.Zowe.docx)

**Comment by hogstrom** [comment]
I've been working with Vicom Infinity on defining a system for VCU.  the current goals are still fluid.  Base recommendation is for a ZR1 with 3 IFLs and 1 GCP with 512GB memory.

**Comment by jmertic** [comment]
Different project - the class is wanting to contribute to Zowe and needs guidance.

**Comment by hogstrom** [comment]
Closing as this is not an item that needs to be tracked at the ZLC.
