### ISSUE TITLE
Zowe GA 1.0.0 Goals

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#37]
List planned or desired GA 1.0.0 goals, and specify each goal accordingly.

Add goals to this document:
https://github.com/zowe/zlc/tree/ga-feature/releases 

Track children epics/stories:
<TBD>

**Comment by armstro** [comment]
Regarding 1.0 goals - MFA listed but not sure that will be included - need to confirm with squads

**Comment by Tbr00ksy** [comment]
closing out this issue and cleaning backlog.
