### ISSUE TITLE
Achieve CII Best Practices badge

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#38]
https://bestpractices.coreinfrastructure.org/en - needs to be achieved before 1.0 release. Suggest starting to work through as soon as possible.

**Comment by hogstrom** [comment]
In what capacity are you setting this goal for the project?

**Comment by jmertic** [comment]
I'm relaying a commitment made by the Zowe project to the OMP TSC. It's also in the OMP TSC's requirements for an Active stage project.

**Comment by hogstrom** [comment]
Who made this commitment to the TSC?  Ok, it just seems ironic that we discuss this issue this morning (at the project's initiation) and you are opening issues in a dictatorial fashion.  Perhaps, better wording would avoid this kind of confusion.

**Comment by hogstrom** [comment]
I am updating the CII Badge Information inventory to get things kicked off so we can assess where we will be by GA 1.0.  Status tracked in this issue

**Comment by hogstrom** [comment]
Updated all information that is currently available.  Look at the community site on the bottom of th page is the current status.  We're at [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/2226/badge)](https://bestpractices.coreinfrastructure.org/projects/2226).

@jackjia-ibm @MarkAckert @1000TurquoisePogs Please [review]( https://bestpractices.coreinfrastructure.org/en/projects/2226) the Quality and analysis portions as these will require build changes.  Also, please review the other sections for any errors or omissions I made.

**Comment by jackjia-ibm** [comment]
Epic created: zowe/zowe-install-packaging#87

There are few requirements I know we should be met already have no related issues created. Please feel free to update or let me know if there are requirements I missed or issues are placed in wrong repositories. Thanks!

**Comment by MarkAckert** [comment]
parent of zowe/zlc#46
parent of zowe/zowe-install-packaging#87

**Comment by hogstrom** [comment]
100% complete
