### ISSUE TITLE
Provide access to Z/OS instance.

### ISSUE THREAD

**Issue by ghost** [zowe/zac#4]
I am new to mainframes and would like to try out Zowe. However, I don't have access to any Z/OS machines. Please provide a way to try out Zowe.

**Comment by ghost** [comment]
From slack conversation with Joe winchester ,

> ....This is something we’ve got a fair few requests for so we need to start to think about how to do this, whether it’d be private sandbox instances using an emulator on cloud machines, or a shared instance that had Zowe pre-installed that folks could test drive. 

Preferably, a private sandbox so that I may get to experiment with Z/OS environment too.

> Do you want a pre-installed instance to use, and would you be OK with sharing one with other users or want a private one.  How long would you want this for.  

Again, preinstalled with zowe but a private one. As for the duration, a month seems fine.

>What other software would you want on the z/OS instance.

I think, it would be nice if Zowe is combined with the master the mainframe tutorials. Would allow newbies like me to explore the mainframe world better.

**Comment by fbeyl** [comment]
That is ok for people new to mainframe.  I have been for decades on mainframe but would like to convince colleagues, management to modernise z environment. Showing zowe in action without installation would be a great help. So one basic common system should be ok for me.

**Comment by hogstrom** [comment]
This todo is bigger than the ZLC.  I'm not sure what we can do apart from tracking the issue.  I believe this is different than the effort with VCU as that is all about CI/CD

**Comment by hogstrom** [comment]
Update website with a page directing people to resources for private instances.

**Comment by Tbr00ksy** [comment]
@hogstrom
Can we please review the attached proposal from MtM for a hands-on tutorial at the next ZLC meeting?
[Zowe Hands-On Trial.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a907c3157b1d800120a86d4/125516c66e82c728ace21e0d46d29b8d26c2aba881edac0e8b53b0a03b4f267f6b48e13b628ae92dbc56395b4d5a1caa415f5f4df8fd8822a6e43a708a5d58b9d93b5b7c932f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e48c8d4f381f011d8cf75427ed.pptx)
This would be a temporary solution for people without access to z/OS to at least play around with the Zowe Web-UI.

**Comment by fbeyl** [comment]
Any news on this trial?

**Comment by Tbr00ksy** [comment]
@fbeyl we have made some progress, but the functionality is limited to the Web UI component. I have updated our website to provide a "Hands on Tutorial"... it is not a trial, as it is limited to the function described in the tutorial.
<img width="1036" alt="screen shot 2018-10-25 at 12 24 58 pm" src="https://user-images.githubusercontent.com/36775778/47515558-318bdb80-d851-11e8-8460-c88eb2233b44.png">
Link to the hands on tutorial is here: https://developer.ibm.com/tutorials/zowe-step-by-step-tutorial/

**Comment by hogstrom** [comment]
This issue is being worked at the OMP for all projects.  The ZLC will be working on this effort but not driving it.
