### ISSUE TITLE
Process - Project Planning (PI Planning)

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#40]
Is it worthwhile to consider a project wide planning cadence for after Zowe GA 1.0.0? Something very similar to, if not exactly, SAFE PI Planning?

**Comment by Tbr00ksy** [comment]
@MarkAckert , the on-boarding squad was thinking the same thing. There is an OMP Marketing Committee Meeting tomorrow (Friday 1.12.19) and we will be proposing the following "Open MeetUp":
https://ibm.box.com/s/tvobjzbn4xes4t6p9cebyhivq7e79v37

Could we get @Kyle-Woodworth, Kim A, BJ S and @jmertic (or someone from LF with experience running a MeetUp in open source) to guide us through how to organize and run one?

**Comment by hogstrom** [comment]
@Tbr00ksy @MarkAckert my vote is YES.  Who has the ball on this issue.  I'll move it to in process.

**Comment by Tbr00ksy** [comment]
@MarkAckert @hogstrom what is the best way to get this initiated? Should each squad prepare to present their overall 2019 goals to the ZLC and then propose a set of objectives that they want to accomplish in each quarter? Thoughts?

**Comment by Kyle-Woodworth** [comment]
I would encourage that.  If the goal is eventually to have Zowe running in PIs, I can absolutely help; but, that's a longer term goal.

To satisfy the immediate ask, as I understand it, let's try asking each Squad to give a few high level objectives illustrating what they can do in 12 weeks.  12 weeks after PI planning, we'll be closing Broadcom's PI, so it'll align closely.

Thoughts?

**Comment by hogstrom** [comment]
Should we convert the ZLC to the Agile Release Train for Scaled Agile Framework e model.

**Comment by hogstrom** [comment]
We discussed a first step to use the community repo to organize features.  @armstro @jplinardon @jlvignaudCA

**Comment by hogstrom** [comment]
Close ... no objections to adoption
