### ISSUE TITLE
"Built on Zowe" Website section

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#41]
We should consider a section on the Zowe website which references products that are "built on Zowe" or "built with Zowe". This can demonstrate an ecosystem of downstream products that leverage the open source community. Need to investigate process for accepting products into the public display.

**Comment by MarkAckert** [comment]
@Tbr00ksy @armstro FYI on this topic. This just came up in adhoc discussions and may be a point of interest for Zowe around or after 1.0.0 GA; wanted to capture it in an issue.

**Comment by Tbr00ksy** [comment]
@MarkAckert this is a great idea and is part of the on-boarding squads vision as well. We were calling it an "App Directory" or "Marketplace." However, there is non-trivial work required to document what a "Zowe Compliant" app is and how we measure that, how we "certify" that is it compliant, and issuing some sort of badge... 

We thought it would be a great 2019 initiative - post 1.0.0 GA. But we'd be happy to discuss how we could incorporate this in 1.0.0 if there is a strong need for this.

**Comment by hogstrom** [comment]
Folding into #52 as an activity as part of that issue.
