### ISSUE TITLE
Zowe - Automated License Scanning

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#42]
Currently the Linux Foundation / Open Mainframe Project is responsible for running licensing and dependency compliance scans against Zowe repositories, and candidate repositories to be donated to Zowe. 

We should discuss if there's any automation the Zowe Org can setup to scan ourselves independently and produce reports that we can evaluate and forward to the LinuxFoundation / OMP. This would allow us to scan frequently as part of our build process, and to independently review candidate repository contributions.

**Comment by hogstrom** [comment]
@jackjia-ibm is this completed ?

**Comment by MarkAckert** [comment]
@hogstrom I'm working on this currently in support of the 1.0.0 release, but complete automation will be post 1.0.0.

**Comment by hogstrom** [comment]
Leaving open for now.  Look for an update in two weeks on May 15.

**Comment by hogstrom** [comment]
@MarkAckert moving to install-packaging

**Comment by MarkAckert** [comment]
Issue moved to [zowe/zowe-install-packaging #472](https://github.com/zowe/zowe-install-packaging/issues/472) via [**ZenHub**](https://www.zenhub.com/)
