### ISSUE TITLE
Discuss - DB2 Plugin Dependencies

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#48]
Summary:

The DB2 plugin utilizes the dependency ibm_db, an open source MIT-licensed module which at install time downloads proprietary ODBC binaries that require a client-side license to run. For our offline CLI installation package with DB2, we currently redistribute the ODBC binaries. We need to review our strategy for this plugin and its packaging.

Some options: 
-keep repackaging odbc binaries, but note the terms of the license as part of a commercial install and point users to rocket/ibm doc for acquiring the client license. install works, plugin usage fails until license is fulfilled. 
-require users to provide the binaries + license themselves. We must test & doc how this process works for our plugin.
-try to get an exemption for ODBC license usage in Zowe
-refactor DB2 to use some other technology (no known tech at time of writing)

**Comment by MarkAckert** [comment]
@zowe/zlc @SujaySolomonCA @alvin-tan @dkelosky 

I create a Waffle issue based on an e-mail thread. We should discuss this during our normal ZLC call.

**Comment by MarkAckert** [comment]
@jmertic @SujaySolomonCA @Tbr00ksy 

John - Could you weigh in on the distribution strategy outlined below for the CLI DB2 Plugin - assuming the plugin hosting is not provided by the OMP for the moment. Is the strategy in compliance with open source licensing and dependency management practices?

Quick recap - one DB2 plugin dependency (ibm_db, MIT License) downloads ODBC binaries (proprietary license) from a public domain at install time. These binaries require a client-side license to operate, which we do not provide.

1. For users who install via the internet, leave everything as-is. The ibm_db plugin downloads ODBC per normal operation. Install documentation points users to external doc for obtaining ODBC client-side license.
2. For users who install via our bundled ZIP (offline install), do not repackage ODBC binaries. The user must download and provide these binaries themselves. Zowe install doc should point users to external doc detailing how to download the ODBC binaries, and where to obtain client side licenses.

**Comment by jmertic** [comment]
I presume this is the package you are speaking of?

https://www.npmjs.com/package/ibm_db

**Comment by MarkAckert** [comment]
Correct, with the ODBC binaries I'm speaking of here: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

(As detailed in the ibm_db package)

**Comment by jmertic** [comment]
OK - thanks for that.

Second question - can you detail the differences between "install via internet" and "install via our bundled ZIP"?

**Comment by MarkAckert** [comment]
Install via Internet
-The user installs the CLI and plugins via npm commands which requires access to the public npm registry (https://registry.npmjs.org), and for the moment, CA's bintray server (https://api.bintray.com/npm/ca/brightside). E.g., 'npm install @brightside/core@next', 'zowe plugins install @brightside/cics@next'. 

Due to some users having restrictive firewalls that disallow the public npm registry from being accessed, the offline package:
-Packs all Zowe CLI packages (core, cics, [db2 withheld]), including their dependencies, into a ZIP archive.
-The user issues npm install commands against the packed components (e.g., 'npm install zowe-cli-2.0.0.tar.gz'; 'zowe plugins install zowe-cics-plugin-2.0.0.tgz'). Installs complete without a problem as all dependencies were packed into the tar files.

**Comment by MarkAckert** [comment]
After consultation with the ZLC and OMP, we determined that repackaging the ODBC binaries would not be in the best spirit of open source, so we are shipping **just** the DB2 plugin. We document steps to acquire the ODBC binaries+ licenses in the Zowe DB2 Plugin installation guide.

This DB2 packaging structure is shipped as of Zowe 0.9.3.
