### ISSUE TITLE
Zowe.org Contribute Page Refresh

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#5]
The contribute page (https://zowe.org/contribute/) could be revamped in several ways:

- [x] Add links and descriptions on the slack channels
- [ ] Add graphic for squads and brief description of how the interact? 
- [ ] Add link to squad Waffle boards/backlog
- [ ] Add link to groups.io for list of list of scheduled squad meetings

**Comment by Tbr00ksy** [comment]
Review issue #10

**Comment by Tbr00ksy** [comment]
Need to note that the only way to get calendar invites to community meetings is to be part of the zowe-dev mailing list.

**Comment by hogstrom** [comment]
This issue was moved to zowe/docs-site#76
