### ISSUE TITLE
Zowe Conformance Program

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#52]
We need to think about what a Zowe Compliance program looks like. What are the benefits of being Zowe compliant? What metrics will we use to measure compliance? How is it enforced? etc.

**Comment by hogstrom** [comment]
I’d suggest making a proposal.  Is this really for people to use a “Powered by OMP Zowe” ?

**Comment by Tbr00ksy** [comment]
@hogstrom great LOTR quote! I want to work on putting a proposal together and am looking for help. I'm curious if @jmertic might have some cookie cutter compliance programs from the LF that could be a starting point. I'm also investigating other programs to get a feel for what ours might look like, or what consumers might expect to see. 

Apple: https://developer.apple.com/app-store/review/guidelines/
Android: https://developer.android.com/distribute/best-practices/launch/launch-checklist

And I agree, I think this compliance program would have a few benefits including:
- rights to use the Zowe mark "powered by Zowe"
- have the ability to be listed in the Zowe App Directory, "market place" (when we get there)
- ensure quality and function within the framework
- etc...

**Comment by Joe-Winchester** [comment]
One thing that I'm wondering/worrying is that Zowe itself isn't actually Zowe compliant !  I think the idea of us working backwards from what we want Zowe compliance to be (architecturally, install experience, operational experience, ..) will be great because it'll force us to work from the outside for how an end user will expect Zowe components to behave, and from there we can start to drive the base towards that cohesion.

**Comment by jmertic** [comment]
Some bits here for the larger group.

0) Let's center on the term 'conformance', not using 'certified' or 'compliant'. The latter two terms have different meanings that imply slightly different intentions than what this program would be.
1) Zowe conformance will likely come in two flavors ( naming is still a WIP )

- Zowe Conformant Distribution, which would be the Zowe open source project components plus optionally any other commercially or open source additions that are bundled by a vendor and shipped as a product. I'd suspect that out of the gate IBM, CA, and Rocket would each be shipped a Zowe Conformant Distribution.
- Zowe Conformant Application, which are applications that are designed to integrate with any Zowe Conformant Distribution.

2) To enable both of those programs to launch, we'd need from the ZLC:

- Clear definition of the integration points for Zowe. We don't need every last one defined now, but certainly focus on the ones where the various squads would expect integration to happen. This can easily evolve over time.
- Alignment on what a Zowe distribution should and should not have ( required vs optional components ).

3) Any Zowe mark usage would be driven from the Zowe Conformance program.

Hopefully this clears things up. Happy to address any questions/concerns.

**Comment by hogstrom** [comment]
@Tbr00ksy next steps here ?

**Comment by Tbr00ksy** [comment]
@hogstrom we need to as a community align around distribution which we can then use to influence the conformance program. Once we have the distribution strategy set we can take that to the OMP board to for them to help define "Zowe Conformant Distribution" while the on-boarding/ZLC can work towards defining "Zowe Conformant Apps". 

Top priority right now needs to be around distribution and packaging strategy.

We are gathering ideas here: https://ibm.box.com/s/3qj5znd5ipp2pqiy65gy2kacir8mho54

**Comment by Tbr00ksy** [comment]
Created PR in the release management repo: https://github.com/zowe/release-management/pull/1

**Comment by hogstrom** [comment]
Change issue to Conformance from Compliance.  
John will take this issue and we will defer this issue.  Needs to be completed prior to 1.0.
Get an update on 11/14/2019

**Comment by Tbr00ksy** [comment]
Updated conformance program location to this branch: https://github.com/zowe/zlc/blob/Conformance/process/conformance

**Comment by Tbr00ksy** [comment]
For the conformance program, does it make sense for us to build out an exhaustive (ideal) list of things we believe a Zowe compliant application should be (think about it from the broader - 2000 ft - ecosystem perspective)? We can then pair it down and break the ideal scenario into different levels (bronze, silver and gold). Taking this approach would help the community gain visibility into our conformance roadmap items.

**Comment by jmertic** [comment]
Good points Tim - wondering if the task agenda Steve laid out is inline with what you were thinking or if you had something else in mind. See attached.

[Conformance Program - Sample Task Agenda.docx](https://github.com/zowe/zlc/files/2627675/Conformance.Program.-.Sample.Task.Agenda.docx)

**Comment by Tbr00ksy** [comment]
Updated link to where conformance program is being developed: https://ibm.box.com/s/401s4s2rdpkgxekhu53zpe3ss53b2jlk

**Comment by jmertic** [comment]
Hi! I've not seen any updates on this in several weeks. What's the latest status?

**Comment by Tbr00ksy** [comment]
Updates on the CLI outline here: https://github.com/zowe/zowe-cli/blob/conformance/docs/cli-conformance.md

Updates on the API ML outline here: https://github.com/zowe/api-layer/blob/conformance/docs/conformance.md

**Comment by dkelosky** [comment]
@jmertic @Tbr00ksy is this conformance plan modeled after something similar?  In a random sampling of popular, extensible "things":  VS Code [Extensions](https://code.visualstudio.com/api), [angular](https://angular.io/) apps, and [WordPress ](https://wordpress.org/plugins/browse/featured/) - I'm not finding anything analogous, e.g. a similar conformance program.  

Are end users requesting Zowe conformance?  Am I missing something else entirely?

An alternative approach is to allow users to install / use popular Zowe extensions (via number of npm downloads or GitHub stars) or download extensions published by more official entities like Rocket, IBM, or Broadcom.

**Comment by jelaplan** [comment]
Is there a vision for how conformance is enforced? Who decides whether distribution or application is conformant?

**Comment by jelaplan** [comment]
> @jmertic @Tbr00ksy is this conformance plan modeled after something similar? In a random sampling of popular, extensible "things": VS Code [Extensions](https://code.visualstudio.com/api), [angular](https://angular.io/) apps, and [WordPress ](https://wordpress.org/plugins/browse/featured/) - I'm not finding anything analogous, e.g. a similar conformance program.
> 
> Are end users requesting Zowe conformance? I'm I missing something else entirely?
> 
> An alternative approach is to allow users to install / use popular Zowe extensions (via number of npm downloads or GitHub stars) or download extensions published by more official entities like Rocket, IBM, or Broadcom.

@dkelosky are suggesting a rating scale so that the Zowe users can rank / rate components, etc.?

**Comment by Tbr00ksy** [comment]
@dkelosky great question. Here are a few conformance programs that are part of the LF that have a similar program structure as to what is being proposed for Zowe:

K8: https://github.com/cncf/k8s-conformance

ODPi: https://www.odpi.org/wp-content/uploads/sites/9/2019/02/ODPi-Egeria-Conformance-Program-%E2%80%93-Terms-and-Conditions.pdf

We have had several requests from ISVs to provide a clear path for commercial and free application to participate in the Zowe framework. One organization wants to expose APIs to commercial offerings into the API ML. Another organization wants to modernize an existing application using the web-UI and to make use of the launch-in context. They then want to use the Zowe brand and logo to promote their offering. 

@jelaplan the OMP/Linux Foundation would be responsible to enforcing conformance. They are also the vendor neutral organization that would review and approve applications for conformance (similar to how it is implemented for k8). It would be the Zowe community's responsibility to develop conformance criteria and for the LF to enforce/manage.

**Comment by dkelosky** [comment]
Thanks for the references @Tbr00ksy !  It's helpful to have an analogous example to check out

**Comment by Tbr00ksy** [comment]
Link to DRAFT Web-UI: https://github.com/zowe/zlux/blob/conformance/docs/app-conformance.md
Link to DRAFT CLI: https://github.com/zowe/zowe-cli/blob/conformance/docs/cli-conformance.md
Link to DRAFT API: https://github.com/zowe/api-layer/blob/conformance/docs/conformance.md

**Comment by Tbr00ksy** [comment]
@Joe-Winchester @OnnoVdT will you look at what it means to be a Zowe conformant distribution? I believe this will relate to the Cupids work.

**Comment by hogstrom** [comment]
ZLC Notes: @Tbr00ksy looking forward to how to programmatically validate conformance.

**Comment by OnnoVdT** [comment]
From a distribution standpoint, I think conformance is very simple. Any Zowe extender needs to either mention where core Zowe (base and its service) can be obtained, or include an unmodified copy that is made available by Zowe.org.  If the extender only provides a non-SMP/E packaged version of their code, the reference/inclusion of core Zowe must be the core Zowe convenience build pax file, the SMP/E FMID and PTFs are optional.  If the extender provides a SMP/E packaged version of their code, the core Zowe reference/inclusion must be the FMID and PTFs, the pax file is optional.

**Comment by hogstrom** [comment]
Asked members to review these proposals and provide feedback to Tim

Link to DRAFT Web-UI: https://github.com/zowe/zlux/blob/conformance/docs/app-conformance.md
Link to DRAFT CLI: https://github.com/zowe/zowe-cli/blob/conformance/docs/cli-conformance.md
Link to DRAFT API: https://github.com/zowe/api-layer/blob/conformance/docs/conformance.md

**Comment by Tbr00ksy** [comment]
I pulled all the draft content together and created a full view of what the conformance program might look like here: https://wiki.zowe.org/x/D4Ag

To edit this content you must first create a LF account by clicking the login button in the top left corner:
<img width="290" alt="Screen Shot 2019-05-28 at 10 21 05 PM" src="https://user-images.githubusercontent.com/36775778/58524643-eba44680-8196-11e9-8928-09e9f273d095.png">

**Comment by Tbr00ksy** [comment]
https://wiki.zowe.org/display/ZCP/Zowe+Conformance+Program
