### ISSUE TITLE
Allow CLI as separate download

### ISSUE THREAD

**Issue by armstro** [zowe/zac#54]
Simplification of install steps for CLI - today it requires unpax of the CLI from the Zowe convenience build and then download - proposal is to  have separate CLI package so unpax not needed

**Comment by MarkAckert** [comment]
@armstro @Tbr00ksy @nkocsis 

We have a separate CLI package already but do not host/present it on any public website. What is the best place for allocating work to expand on the zowe.org website to present the CLI package? Onboarding squad or elsewhere? The CI/CD squad can expand automation to support package creation + deployment.

**Comment by hogstrom** [comment]
Supported by the ZLC ... votes and comments below:

[1] Matt Hogstrom  
[1] Bruce Armstrong  
[1] Jean-Philipe  
[1] Sean Grady  
[1] Mark Ackert  
[1] Jean-Louis
Package and distribute the CLI seperate from the main Pax.  
Same release cadence as Zowe major version. 
Target for 0.9.4

See https://github.com/zowe/zlc/meetings/2018-10-31/Agenda.md for other information.
