### ISSUE TITLE
Signing of interim builds

### ISSUE THREAD

**Issue by hogstrom** [zowe/zac#68]
For non major releases where we drop n.n.n like 0.9.4, 0.9.5, etc I propose that we have a set of signing keys that the build team can use to validate the artifacts for governance purposes.  I don't think that these interim builds are really "official" releases and so the signing can be done by the build team.

This item is to open this idea for discussion and identify alternatives if needed.  

Ideally, for releases we need a process for signing that spreads the responsibility for signing and does not rely solely on one person.

**Comment by jackjia-ibm** [comment]
Related to https://github.com/zowe/zowe-install-packaging/issues/402

**Comment by hogstrom** [comment]
@jackjia-ibm has a set of keypairs for signing interim releases.
