### ISSUE TITLE
Zowe.org Home Page

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#7]
Can we consider rethinking the Zowe.org home page? The "Why Zowe?" seems to be addressed by the OMP's static project site. Perhaps it would be more useful to give a brief project overview of "What" Zowe is instead.

**Comment by nannanli** [comment]
Some other suggestions for the home page:
- Can we change "Resources" to "Docs" which sounds more obvious? 
- There is a typo in "GITHub" when you click "Contribute". Should be "GitHub".

**Comment by hogstrom** [comment]
Tim, are you willing to lead here or should we close this item and bring it back later?

**Comment by Tbr00ksy** [comment]
@hogstrom I am currently reworking this with @jayenzi. We have several working items in our backlog at the moments and are tracking them here: https://ibm.box.com/s/jxdu3nxkpmvq2cgmpjj4l1io91tt36m7
(all future issues will use the appropriate Git Repo/Waffle board that I have write access to)
