### ISSUE TITLE
z/OS Message ID Structure for Zowe

### ISSUE THREAD

**Issue by hogstrom** [zowe/zac#73]
## History
As the open sourcing of the ZSS has progressed it has highlighted the need for us to work with the IBM Message ID structure where applicable.  I'm going to presume that some may not be fully aware of z/OS messages so a quick pre-amble, then the challenge and recommendation for discussion.

Messages are a core theme on z/OS and are issued when specific events occur.  These messages are sent to a variety of destinations like the master console, JES log, System Log, specific consoles and Job Logs.  

The messages are intended to document, inform and are also used to drive automation through systems like IBM's System Automation, CA Technologies' Ops MVS or BMC's AutoOperator.  To be useful for automation, event technologies rely on the well formed message structure to change automation states, drive actions.  

Zowe needs to generate a set of messages that are consistent with this long-standing approach.  **Not all messages that flow from Zowe need to follow this** (debug logs, application messages, etc.)  That said, most consumers and other ISVs will expect compatibility with this approach.

## Format

The net is that messages for our purposes are: 

CCCSnnnnt

__CCC__ = Message prefix.  Each of these is three characters long and generally refers to a product.  A product outside of IBM has to reserve the use of the prefix to avoid colliding with other products.

__S__ = for Zowe this is a sub-system identifier.  We need to identify these.  Here are the components I can think of off the top of my head.

A - API Mediation Layer
C - Zowe Command Line
D - Zowe Desktop
E - Explorer (not sure if this is needed as Explorers are currently more application specific.  If we elevated them to part of the Desktop (like Finder on Mac or Explorer on Windows this would make sense as a component)
S - ZSS subsystem services

On reserve right now from IBM are the following prefixes:

__OMP__ - I reserved this generally for the OpenMainframe  Project 
__ZWE__ - For Zowe use.

Are there other prefixes we should reserve?

## More detail on message formats

The message structure is fairly straight forward.  Quoting from the [IBM Messages manual](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.ieam100/msgfmt.htm):

> The message body consists of three parts: the reply identifier (optional), the message identifier, and the message text. The following formats are possible:
> 
> id CCCnnn text
> id CCCnnns text
> id CCCnnnns text
> id CCCnnnnns text
> id CCCSnnns text
>  
> **id**
> Reply identifier: It is optional. It appears if an operator reply is required. The operator specifies it in the reply.
> **CCCnnn, CCCnnns, CCCnnnns, CCCnnnnns, CCCSnnns**
> Message identifier.
> **CCC**
> A prefix to identify the component, subsystem, or product that produced the message. The prefix is three characters.
>
> **S**
> The subcomponent identifier, which is an optional addition to the prefix to identify the subcomponent that produced the message. The subcomponent identifier is one character.
> **nnn, nnnn, nnnnn**
> A serial number to identify the individual message. The serial number is three, four, or five decimal digits.
> **s**
> An optional type code, which is one of the following:
>
> **A**
> **Immediate Action**: System operator action is always immediately required. A system operator must do something now, such as mount a tape cartridge or attach a DASD.
> The associated task does not continue until the requested action has been taken.
> 
> **D**
> **Immediate Decision**: System operator decision/action is always immediately required. All system messages issuing the “D” type code must enumerate the available options. A system operator must make a decision now by selecting a reply from the enumerated options and responding to the system immediately.
> The associated task does not continue until the operator communicates the decision to the system.
> 
> **E**
> **Eventual action**: System operator action will be required. A system operator must eventually an appropriate action.
> The associated task continues independent of system operator action.
> 
> **I**
> **Information**: System operator action is not required. Communication in this category is for advisory purposes and may provoke system operator action.
> The associated task continues independent of system operator action.
> 
> **S**
> **Severe error**: Severe error messages are for a system programmer.
> **T**
> **Terminate**: The IEBCOPY program terminates.
> **W**
> **System Wait**: System operator action is always required immediately. A system catastrophe has occurred (hardware or software or both). The system must be re-IPLed to continue or a major subsystem must be re-started.
> **text**
> **Text**: The text provides information, describes an error, or requests an operator action.

_More to come, interrupted_

**Comment by hogstrom** [comment]
Net is here are some sample messages:

ZWEA001I API Mediation Layer Initialization in Progress
ZWEA002I API Mediation Layer Initialization Complete
ZWEA003E Certificate __*my certificate*__ will expire in __*nn*__ days.  
ZWED001I Zowe Desktop Initialization in Progress
ZWED002E Failed to load plugin __*a plugin that should have been loaded*__ 
ZWES002I Zowe ZSS Initialized on system __*sysid*__ on sysplex __*sysplex__* at ...

**Comment by 1000TurquoisePogs** [comment]
Two questions:
1. Can we also use the X prefix for the ZSS cross memory server? It cooperates with ZSS but has an independent lifecycle.
2. Trying to figure out when the D-type message applies. The zlux code logs with the ID of each plugin, so that it is easy to figure out what extensible unit is causing a behavior, so you see this sort of log format:
[9728] [2019-01-14 16:27:55.452 **_unp.network** INFO] - (HTTPS)  Listening on 0.0.0.0:8544
[16308] [2019-01-14 16:27:55.453 _unp.network INFO] - (HTTPS)  Listening on 0.0.0.0:8544
[16308] [2019-01-14 16:28:14.382 **org.zowe.terminal.proxy.tn3270data** INFO] - Saw Websocket request, method=GET
[9728] [2019-01-14 16:28:26.750 org.zowe.terminal.proxy.tn3270data INFO] - Saw Websocket request, method=GET


Perhaps this is what you are expecting?
[9728] [2019-01-14 16:27:55.452 **_unp.network** INFO] - **ZWED001I** (HTTPS)  Listening on 0.0.0.0:8544
[16308] [2019-01-14 16:27:55.453 _unp.network INFO] - **ZWED001I** (HTTPS)  Listening on 0.0.0.0:8544
[16308] [2019-01-14 16:28:14.382 **org.zowe.terminal.proxy.tn3270data** INFO] - **ZWED002I** Saw Websocket request, method=GET
[9728] [2019-01-14 16:28:26.750 org.zowe.terminal.proxy.tn3270data INFO] - **ZWED002I** Saw Websocket request, method=GET

**Comment by hogstrom** [comment]
I think X would be fine for the X-mem server if needed.  If they are tightly coupled then we could just use ZSS and have messages that clearly identify the component in the text.  Whatever is most intutitive.

Using the first example I think :
[9728] [2019-01-14 16:27:55.452 _unp.network INFO] - (HTTPS) Listening on 0.0.0.0:8544 
Becomes:
ZWED001I (HTTPS) Listening on 0.0.0.0:8544
The preamble of date and time will be supplied by the appropriate routing code.  If this is a log message then we would have to provide the date / time I think .  For console messages via WTOR the preamble is provided z/OS.  For instance, like
> Type Code . Routing .  System .    Julian .   Time
> N                   0040000 TVT7050  19014    18:22:01.29          00000090

**Comment by ifakhrutdinov** [comment]
Matt, ZSS is one of the users (the major one) of the cross-memory server. But other applications can call it too. That is, it doesn't depend on ZSS.

**Comment by hogstrom** [comment]
We need to balance whether it needs its own component and 9999 messages.  If we're creating 12 messages then we're probably using our message real estate more efficiently.   Today it makes sense, does it still make sense 4 years from now and 32 messages after growth (I really don't know the answer but just communicating my thought process).  If the community feels that identifying this component seperately makes sense then that's fine.  I wasn't aware of its existence until last week in all the time we've been working on Zowe so I'm still processing this component and its reach and impact.

**Comment by ifakhrutdinov** [comment]
Initially I was looking at the message formats provided by the IBM reference under "The following formats are possible" which didn't list CCCSnnnnt (subcomponent + 4 digits + type). If we can use CCCSnnnnt, then the number of message IDs should probably be enough under a single subcomponent ID.

**Comment by hogstrom** [comment]
Zowe is responsible for the OMP and ZWE message prefixes.  If other prefixes are needed, Please open an issue and we will pursue them.

Added @nannanli as I think this becomes a doc squad action and one for each project to document and include messages that follow this format.

II'll be moving subsystem assignments into messageManagement.md in zowe/zlc/process this evening

**Comment by hogstrom** [comment]
The messages and codes manual was not clear on the limits of the messages if you included a component.  I've found several messages that support the format we would like to use.

For Example, this is issued by the z/OS product DFSMS

__ADRY0001I__ FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS nn hh:mm:ss mm/dd/yy

The three letter prefix for ADR (DFSMS)
__Y__  component identifier
__0001__ 4 digits for the message number
__I__ Type code (in this case informational).  

Total message length is 9 characters.

**Comment by ifakhrutdinov** [comment]
Regarding the type codes. I've discussed that with a colleague and the ones mentioned in the description are intended for z/OS components.

Usually application use these:
I - informational message
E - error
W - warning
S - severe error

I think it would make more sense to use them, especially for web code which doesn't have "System Wait".

**Comment by hogstrom** [comment]
E as an error is probably the way most people understand E ... that isn't how IBM defines it but I'm fine with it.   Error's generally require action so its the same thing I think

**Comment by hogstrom** [comment]
@ifakhrutdinov Irek, so, is one subsystem work for you ?  Which letter (if there is one) works for you?

**Comment by ifakhrutdinov** [comment]
@hogstrom, yes, I think we can share message IDs with the non-cross memory ZSS code, i.e. ZWESnnnnt. 

@1000TurquoisePogs, is S the letter what we'd like to use for ZSS?

**Comment by 1000TurquoisePogs** [comment]
I think S is fine due to thinking that we won't go through 9999 messages for these components, and that despite the technical differences people are likely to group ZSS & the cross memory servers as one logical component of Zowe.

**Comment by fbeyl** [comment]
Since ZWE is reserved it's no longer about application messages but system messages and in that case one should stick to IBM Message structure for 'type'.

**Comment by fbeyl** [comment]
Since ZWE is reserved it's no longer about application messages but system messages and in that case one should stick to IBM Message structure for 'type'.

**Comment by hogstrom** [comment]
Documented and PR created https://github.com/zowe/zlc/pull/75
