### ISSUE TITLE
Review/Approve Zowe 1.0 Messaging

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#76]
Can the ZLC please review and approve the Zowe 1.0 messaging which will be used in a variety of ways including press releases and social promotions. 

Please review and make changes to the boxnote here: https://ibm.box.com/s/eh5pxhodvp38cwb9uvnnu9i5vjja9468

The 1.0 campaign planning doc is here: https://docs.google.com/document/d/1GZBziZb9YNopb8PpSW-irBdUjhIQVRpAISUgS_1UcKU/edit?usp=sharing

Please reviewing and making the appropriate edits, please approve by commenting on this issue.

**Comment by armstro** [comment]
Made some changes to the messaging in box - hottest issue in my opinion is what to say about non-breaking changes - I made an attempt to say but policy needs to be documented somewhere (if not already) and not just in a marketing bullet.

**Comment by Tbr00ksy** [comment]
Does anyone object to me closing out this issue? The OMP is moving forward with the content that was provided.

**Comment by armstro** [comment]
I think ok to close but we (ZLC) should review the OMP press release for accuracy and see which of the items the picked up to use from the messaging dock. Note to those who have not looked we removed the 1.0 claim on non-breaking changes. I think we still need to encourage non-breaking changes for all releases (and only allow on version boundaries) but no need to make the claim with 1.0 (and doubtful such a claim needed to be in press release/marketing points.)
