### ISSUE TITLE
Generic PPT Templates

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#79]
During Zowe Sprint Playbacks, and possibly other user engagement sessions - the member companies of the Zowe project have PPT slides with copyrights respective to the individual companies (Broadcom, Rocket, etc.).

Could the ZLC provide a set of generic templates? What copyright info, if any, should be present on the slides?

**Comment by Tbr00ksy** [comment]
Here is a link to the OMP/Zowe PPT template. There are no need for copyright on community material.
Boxlink: https://ibm.box.com/s/b63hgcs079x71d9jxe3y27orzt4nu683
[Zowe:OMP PPT Template.pptx](https://github.com/zowe/zlc/files/2861352/Zowe.OMP.PPT.Template.pptx)

**Comment by MarkAckert** [comment]
Thanks Tim, I added the template to the community repo here: https://github.com/zowe/community/tree/master/Templates . I will move this issue to done.
