### ISSUE TITLE
Zowe Charter

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#8]
Can we look at creating a better way for people to view/consume the Zowe charter? i.e. how to propose a new project, how to become a committer, how to become a leader, etc.

**Comment by hogstrom** [comment]
John volunteered to take the PDF for the project and ready it for publishing on the website.

**Comment by hogstrom** [comment]
Items have been posted to the Zowe website.  for additional changes they will be track individually going forward.
