### ISSUE TITLE
Form temporary Installation Squad

### ISSUE THREAD

**Issue by nkocsis** [zowe/zac#80]
A temporary squad should be formed to architect the install. This would include:
- packaging of various components
- ability to apply ptfs or delta installs without compete re-install
- will it be SMPE or other

**Comment by Joe-Winchester** [comment]
Collecting the requirements and thoughts for install in the https://github.com/zowe/zowe-install-packaging/wiki/Install-Experience

**Comment by hogstrom** [comment]
@Joe-Winchester Is this issue still needed ?  My understanding is that this is now the Cupid squad.  Closing for now, please re-open if this is incorrect.
