### ISSUE TITLE
Discuss the removal of old releases from Zowe.org

### ISSUE THREAD

**Issue by nkocsis** [zowe/zac#82]

**Comment by nkocsis** [comment]
Remove all pre-1.0.0 binaries as of May 31. Update Zowe.org to announce this removal

**Comment by nkocsis** [comment]
Encourage consumers to use 1.0.0 and above

**Comment by Tbr00ksy** [comment]
Proposed beta deprecation notice language:

"
Zowe v0.8.x and v0.9.x Beta Deprecation

For those of you who are using Zowe beta releases v0.8.x and v0.9.x, the Zowe community is ending their distribution and encouraging all Zowe users to move to v1.x.x.  The v0.8.x and 0.9.x distributions were licensed under a joint early programs license by IBM, Rocket Software and CA Technologies (Broadcom) and contained proprietary (non-EPL) licensed code.  Zowe v1.0.0 has achieved the required refactoring and re-licensing and is now 100% open sourced (EPL v2.0). Zowe will be removing and archiving the v0.8.x and v0.9.x releases from Zowe.org by May 31st, 2019 and we hope you will upgrade to the newest release of Zowe.
"

^^^ I would like to submit this post to the OMP blog site and link to it from Zowe.org's announcement header. 

Please let me know if you all approve the above. If so, I will move forward to implement.

**Comment by hogstrom** [comment]
Closing Per Nicks request
