### ISSUE TITLE
New Zowe Sub-Project Proposal - IMS Operations API

### ISSUE THREAD

**Issue by hfungibm** [zowe/zac#85]
- Name of project (must be unique within Zowe)
IMS Operations API

- Project description (what it does, why it is valuable, origin and history)
IMS Operations API allow users to use RESTFul APIs to submit IMS commands for managing IMS resources in support of application deployment.  The IMS Operations API provides the ability to manage IMS program resources for application programs, manage and query IMS application program resources that have been scheduled for execution, and control availability of IMS message and application processing regions.  More specifically, initial contribution will include ability to: <br>
Create and define IMS program resources for application programs
Update, start or stop IMS program resources
Query information about IMS program resources
Delete IMS program resources
Create an IMS transaction code that associates an application program resource to be scheduled for execution
Update, start or stop IMS transaction resources
Query information about IMS transactions across IMSplex
Delete IMS transactions
Start and Stop IMS message and application processing regions

- Statement on alignment with Zowe mission
Our IMS Operations API aligns with IBM’s initiative to support Zowe open source project for modernizing and enhancing the user experience with mainframe.  This project provides a framework that helps developers to develop and use APIs to manage IMS resources and ease DevOps integration using modern languages and tooling for mainframe. 
The Operations API would be used by the Zowe CLI IMS plugin to submit CLI commands for managing IMS resources

- Sponsor from ZLC (sponsor helps mentor projects)
Bruce Armstrong and Matt Hogstrom

- License and contribution guidelines
Eclipse Public License 2.0 (EPL-2.0)

- Source control
GitHub

- External dependencies
None

- Initial committers
Jerry Li (IBM)
Haley Fung (IBM)
Bryant Panyarachun (IBM)

- Infrastructure requests
None

- Communication channels
Slack

- Issue tracker
GitHub

- Preferred maturity level
Incubator

**Comment by MarkAckert** [comment]
Hi, Is there an existing public Github repository we could investigate and review for licensing compliance and build structure?

**Comment by armstro** [comment]
After presentation today to ZLC plan is as follows - IMS team needs to get approval from IBM internal process to submit, this is target for this week. Per Mark's question above the code will be moved to an open repository for scan by LF....once cleared it will come back to zlc for final vote. @nkocsis to assist IMS team with LF scan point of contact.

**Comment by MarkAckert** [comment]
We will also consider approval of this proposal as including 2 repositories (names not final):
Zowe-IMS-REST-Server
Zowe-CLI-IMS-Plugin

**Comment by hfungibm** [comment]
FYI - looks like IBM internal approval process to take longer as one of the key approver is out of office this week.  I will update again when we are allowed to put out the code in some public GitHub for review.

**Comment by hfungibm** [comment]
Our IBM internal approval completes and now the code is available in the public GitHub for scan.  @nkocsis - can you help with the next step?

**Comment by MarkAckert** [comment]
Hi @hfungibm - was there a build tool previously in use with the ims code, such as maven/gradle? I also see some classes named after Liberty - does this depend on Liberty ? Deploy as a WAR into Liberty? Thanks

**Comment by hfungibm** [comment]
@MarkAckert - The committer IDs are
- itsBryantP (Bryant Panyarachun)
- hfungibm (Haley Fung)
- th365thli (Jerry Li)

**Comment by hogstrom** [comment]
Onboarding complete
