### ISSUE TITLE
Youtube Channel

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zac#9]
Need to determine where we can host our demos, tutorials, etc. Can we have a "featured channel" on the OMP's youtube channel? Or do we need to create our own Zowe youtube channel?

**Comment by hogstrom** [comment]
We need John Mertic to update on the OMP / LF process.

**Comment by hogstrom** [comment]
Send videos to Mae for review and see if this process works.

**Comment by hogstrom** [comment]
Can we close this issue ?
