### ISSUE TITLE
Zowe "vNext" release validation

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#92]
Zowe's active development line has some new features/components that we would like to present on the zowe.org website for "early access" / "beta" / "validation" testing. We should discuss both the generalized process for bringing components/deliverables to the zowe.org website, as well as a specific use case we have right now.

Specific use cases:

Zowe CLI recently renamed @brightside -> @zowe and as a result of breaking dependent plugins (import statements needed to be changed), the CLI increased its major version from 2.x -> 3.x. The CLI API (i.e `zowe zosmf status check`) was not broken. Should we: publish Zowe CLI 2.x (vs some 1.x) on the zowe.org website? What is the flow for finding this build, associated doc, etc.?

Zowe is adopting the IMS REST Server and Zowe CLI IMS Plugin into the organization. How do we present these components to end users for validation, and how do we promote these components into the official build on Zowe.org?

@zowe/zlc @jmertic @Tbr00ksy @armstro @MikeBauerCA

**Comment by hogstrom** [comment]
Mark will have an update on 4-23-2019

**Comment by hogstrom** [comment]
Under active Development

**Comment by hogstrom** [comment]
Merging with https://github.com/zowe/zlc/issues/103
