### ISSUE TITLE
New Zowe Repository - CLI FTP Plugin

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zac#93]
The CLI Squad has another plugin they would like to donate to Zowe - the Zowe FTP plugin. This plugin began as an innovation effort by a member of the CLI Squad, and exposes the following functionality:

* Delete USS files or MVS datasets
* Download USS file, MVS dataset, or Job Output
* List USS files or MVS datasets
* Rename USS files or MVS datasets
* Submit Jobs from Dataset Member
* Upload USS files or MVS datasets
* View USS files, MVS datasets, or Job Output

The source code is staged here: https://github.com/MarkAckert/zowe-ftp-plugin-staging .

@zowe/zlc @jmertic Please review and comment here if you have questions or concerns.

**Comment by hogstrom** [comment]
Next step is for @jmertic to clarify legal issues around binary distributions and will provide an update on 2019-04-23

**Comment by hogstrom** [comment]
Competed

**Comment by hogstrom** [comment]
@MarkAckert to verify dependencies on 3rd party open source.

**Comment by armstro** [comment]
Plugin that donated into Zowe makes use of the zos-node-accessor package from IBM open source: https://github.com/IBM/zos-node-accessor...

**Comment by hogstrom** [comment]
No further action at this time.  Linux Foundation scanned.
