### ISSUE TITLE
Turn on "Require two-factor authentication for everyone in the Zowe organization."

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#96]
LF IT reviewed that this setting wasn't on and strongly recommended that the project do this for security reasons. 

Thinking if the ZLC is good with this, we could have a 30 day grace period and then flip it on. Thoughts?

**Comment by hogstrom** [comment]
+1 from me.

**Comment by armstro** [comment]
I'd like to know more about how this would be implemented before voting.......would it involve use of just a second email address to confirm identity, personal cell, DNA sample?

**Comment by jmertic** [comment]
Check out this...

https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa

Thank you,

John Mertic
Director of Program Management - Linux Foundation
ASWF, ODPi, and Open Mainframe Project
jmertic@linuxfoundation.org
+1 234-738-4571
Schedule time with me at https://calendly.com/jmertic

**Comment by 1000TurquoisePogs** [comment]
-1 for me.
2FA can be nice, if the auth types are nice. Github appears to only have a few, and they all have issues.

1. Phone number, which is great up until there's yet another leak and now robocallers have my phone number again
2. authy: requires my phone number, so the same
3. 1password: not free
4. lastpass authenticator: doesn't work on android without google services framework, which is proprietary.

Edit: Actually, there are other TOTP-compatible apps that are open source. I tried one out (Aegis) which worked, but here's a few: https://search.f-droid.org/?q=totp&lang=en

**Comment by jmertic** [comment]
@1000TurquoisePogs So is the tooling the main issue for you? I think you pointed out there are a ton of open/proprietary solutions ( as well as hardware and software ) which provides flexibility. 

I think the big thing is, we want to ensure everyone's accounts are secure, especially if you have committer access. 2FA is extremely common these days - most LF projects have this requirement and it's usually quite welcomed and encouraged by the community,

**Comment by jmertic** [comment]
I'll also note it's part of the CII badge at the Gold level:

https://bestpractices.coreinfrastructure.org/en/projects/2226?criteria_level=2#changecontrol

**Comment by hogstrom** [comment]
Need to write up a recommendation to start ... for example - Sean to compile the initial list

**Comment by jmertic** [comment]
@hogstrom When can we flip this on?

**Comment by hogstrom** [comment]
Complete
