### ISSUE TITLE
Acclaim badge for Zowe committers

### ISSUE THREAD

**Issue by jmertic** [zowe/zac#97]
We have the ability to issue badges under the LF's Acclaim account ( https://www.youracclaim.com/ ) and thought to help showcase community support the idea of issuing a 'Zowe Committer' badge might be a cool idea. Let me know if y'all are down with this and if so I can get this going.

**Comment by hogstrom** [comment]
Sounds good to me.  You might have a separate OMP badge

**Comment by hogstrom** [comment]
Discussed at ZLC last week.  Proceed
